var work_u_2_34= {
    id: 34,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 320,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 145,
                  left: 270,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "green trees",
                  valid: true,
                },
                {
                  top: 225,
                  left: 70,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " two big houses",
                  valid: true,
                },
                {
                  top: 225,
                  left: 270,
                  width: 150,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " twelve black bags",
                  valid: true,
                },
                {
                  top: 305,
                  left: 70,
                  width: 150,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " two young horses",
                  valid: true,
                },
                {
                  top: 305,
                  left: 270,
                  width: 150,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " four English buses",
                  valid: true,
                },
              ],
            },
           
          ],
        },
      },
       
        {
          top: 350,
          left: 8,
          width: 450,
          height: 350,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 109,
                    left: 230,
                    width: 190,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "you've got a new houses",
                    valid: true,
                  },
                  {
                    top: 150,
                    left: 50,
                    width: 180,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "They’ve got red bikes",
                    valid: true,
                  },
                  {
                    top: 150,
                    left: 230,
                    width: 200,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "They’ve got beαutiful kittens",
                    valid: true,
                  },
                  {
                    top: 195,
                    left: 70,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "They’ve got long tαils",
                    valid: true,
                  },
                  {
                    top: 195,
                    left: 230,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "We’ve got green bαgs",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };