var work_u_2_32 = {
    id: 32,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 370,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 140,
                  left: 70,
                  width: 150,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "fifteen yeαrs old",
                  valid: true,
                },
                {
                  top: 166,
                  left: 45,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " The parrots are young",
                  valid: true,
                },
                {
                  top: 188,
                  left: 45,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " They are two years old",
                  valid: true,
                },
                {
                  top: 223,
                  left: 50,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " The horses are old",
                  valid: true,
                },
                {
                  top: 244,
                  left: 50,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " They αre eighteen yeαrs old",
                  valid: true,
                },
                {
                  top: 310,
                  left: 200,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " twelve (yeαrs old)",
                  valid: true,
                },
                {
                  top: 329,
                  left: 235,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: " αre fifteen (yeαrs old).",
                  valid: true,
                },
                {
                  top: 350,
                  left: 195,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "He's/He is eleven (yeαrs old)",
                  valid: true,
                },
              ],
            },
           
          ],
        },
      },
       
        {
          top: 380,
          left: 8,
          width: 450,
          height: 220,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 60,
                    left: 260,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "fourteen ",
                    valid: true,
                  },
                  {
                    top: 80,
                    left: 265,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "fifteen ",
                    valid: true,
                  },
                  {
                    top: 100,
                    left: 265,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "sixteen ",
                    valid: true,
                  },
                  {
                    top: 120,
                    left: 265,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "seventeen ",
                    valid: true,
                  },
                  {
                    top: 140,
                    left: 265,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "eighteen ",
                    valid: true,
                  },
                  {
                    top: 160,
                    left: 265,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "nineteen ",
                    valid: true,
                  },
                  {
                    top: 80,
                    left: 195,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: " five",
                    valid: true,
                  },
                  {
                    top: 100,
                    left: 195,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: " six",
                    valid: true,
                  },
                  {
                    top: 120,
                    left: 195,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: " seven",
                    valid: true,
                  },
                  {
                    top: 140,
                    left: 195,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: " eight",
                    valid: true,
                  },
                  {
                    top: 160,
                    left: 195,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: " nine",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };