var work_u_2_35 = {
    id: 35,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 320,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 53,
                  left: 140,
                  width: 190,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "They’re red boxes",
                  valid: true,
                },
                {
                  top: 75,
                  left: 150,
                  width: 180,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "They’re brown foxes",
                  valid: true,
                },
                {
                  top: 95,
                  left: 150,
                  width: 180,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "They’re new toyshops",
                  valid: true,
                },
                {
                  top: 167,
                  left: 300,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "toyshop",
                  valid: true,
                },
                {
                  top: 210,
                  left: 280,
                  width: 60,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "horses",
                  valid: true,
                },
                {
                  top: 270,
                  left: 300,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "white",
                  valid: true,
                },
                {
                  top: 290,
                  left: 300,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "big",
                  valid: true,
                },
                
              ],
            },
          ],
        },
      },
       
        {
          top: 320,
          left: 8,
          width: 450,
          height: 260,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 53,
                    left: 110,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "s",
                    valid: true,
                  },
                  {
                    top: 53,
                    left: 320,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "s",
                    valid: true,
                  },
                  {
                    top: 75,
                    left: 110,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "es",
                    valid: true,
                  },
                  {
                    top: 75,
                    left: 296,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "es",
                    valid: true,
                  },
                  {
                    top: 95,
                    left: 110,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "s",
                    valid: true,
                  },
                  {
                    top: 95,
                    left: 296,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "es",
                    valid: true,
                  },
                  
                ],
              },
             
            ],
          },
        },
        
      ],
    };