var work_u_2_25= {
	id: 25,
	paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 350,
        zoom: {
          answers: [
             {
            paths: [
              {
                top: 172,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "Its",
                valid: true,
              },
              {
                top: 195,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "Their",
                valid: true,
              },
              {
                top: 216,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "Their",
                valid: true,
              },
              {
                top: 230,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "Her",
                text: "Their",
                valid: true,
              },
              {
                top: 244,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "Her",
                valid: true,
              },
              {
                top: 266,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "Our",
                valid: true,
              },
              {
                top: 290,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "His",
                valid: true,
              },
              {
                top: 312,
                left: 240,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "Your",
                valid: true,
              },
              
              
            ],
          },
           
          ],
        },
      },
       
        {
          top: 350,
          left: 8,
          width: 450,
          height: 280,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 103,
                    left: 247,
                    width: 20,
                    font:12,
                    height: 16,
                    type: "text",
                    text: "rooms",
                    valid: true,
                  },
                  {
                    top: 125,
                    left: 235,
                    width: 70,
                    font:12,
                    height: 16,
                    type: "text",
                    text: "their toys",
                    valid: true,
                  },
                  {
                    top: 150,
                    left: 230,
                    width: 120,
                    font:12,
                    height: 16,
                    type: "text",
                    text: "Our books are blue",
                    valid: true,
                  },
                  {
                    top: 173,
                    left: 230,
                    width: 180,
                    font:12,
                    height: 16,
                    type: "text",
                    text: "Their bikes αren’t/αre not fαst",
                    valid: true,
                  },
                  {
                    top: 195,
                    left: 230,
                    width: 160,
                    font:12,
                    height: 16,
                    type: "text",
                    text: "Their brothers αre strong",
                    valid: true,
                  },
                  
                ],
              },
             
            ],
          },
        },
        
      ],
    };