var work_u_2_24 = {
    id: 24,
    
    paths: [
      {
      top: 15,
      left: 10,
      width: 450,
      height: 220,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 100,
                left: 230,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "Her",
                valid: true,
              },
              {
                top: 122,
                font:12,
                left: 250,
                width: 20,
                height: 16,
                type: "text",
                text: "Its",
                valid: true,
              },
              {
                top: 149,
                left: 250,
                font:12,
                width: 20,
                height: 16,
                type: "text",
                text: "His",
                valid: true,
              },
              {
                top: 170,
                left: 160,
                font:12,
                width: 20,
                height: 16,
                type: "text",
                text: "Your",
                valid: true,
              },
              {
                top: 170,
                left: 305,
                width: 20,
                font:12,
                height: 16,
                type: "text",
                text: "My",
                valid: true,
              },
              
            ],
          },
         
        ],
      },
    },
     
      {
        top: 235,
        left: 8,
        width: 450,
        height: 350,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 70,
                  left: 146,
                  width: 20,
                  font:12,
                  height: 16,
                  type: "text",
                  text: "MY",
                  valid: true,
                },
                {
                  type: "underline",
                  top: 40,
                  left: 220,
                  width: 140,
                  rotate: -29,
                  text: "",
                  valid: true,
                  id: 1,
                },
                {
                  top: 80,
                  left: 225,
                  width: 8,
                  area: {
                      top: 80,
                      left: 225,
                      width: 8,
                      height: 8
                  }, 
                  underline: 1,
                  type: "checkmark",
                  valid: true
              },
              
                {
                  top: 100,
                  left: 140,
                  width: 20,
                  font:12,
                  height: 16,
                  type: "text",
                  text: "His",
                  valid: true,
                },
                {
                  type: "underline",
                  top: 120,
                  left: 245,
                  width: 80,
                  rotate: 190,
                  text: "",
                  valid: true,
                  id: 2,
                },
                {
                  top: 110,
                  left: 250,
                  width: 8,
                  area: {
                      top: 110,
                      left: 250,
                      width: 8,
                      height: 8
                  }, 
                  underline: 2,
                  type: "checkmark",
                  valid: true
              },
                {
                  top: 130,
                  left: 140,
                  font:12,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "Her",
                  valid: true,
                },
                {
                  type: "underline",
                  top: 106,
                  left: 250,
                  width: 120,
                  rotate: -29,
                  text: "",
                  valid: true,
                  id: 3,
                },
                {
                  top: 140,
                  left: 255,
                  width: 8,
                  area: {
                      top: 140,
                      left: 255,
                      width: 8,
                      height: 8
                  }, 
                  underline: 3,
                  type: "checkmark",
                  valid: true
              },
                {
                  top: 160,
                  font:12,
                  left: 135,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "Its",
                  valid: true,
                },
                {
                  type: "underline",
                  top: 160,
                  left: 275,
                  width: 80,
                  rotate: -10,
                  text: "",
                  valid: true,
                  id: 4,
                },
                {
                  top: 172,
                  left: 275,
                  width: 8,
                  area: {
                      top: 172,
                      left: 275,
                      width: 8,
                      height: 8
                  }, 
                  underline: 4,
                  type: "checkmark",
                  valid: true
              },
                {
                  top: 270,
                  left: 75,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 290,
                  left: 80,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 310,
                  left: 65,
                  width: 20,
                  font:12,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 244,
                  left: 222,
                  font:12,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "Your",
                  valid: true,
                },
                {
                  top: 244,
                  font:12,
                  left: 290,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 265,
                  left: 222,
                  font:12,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "His",
                  valid: true,
                },
                {
                  top: 265,
                  font:12,
                  left: 290,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 290,
                  left: 222,
                  font:12,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "Her",
                  valid: true,
                },
                {
                  top: 290,
                  left: 290,
                  width: 20,
                  font:12,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 310,
                  left: 222,
                  font:12,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "Its",
                  valid: true,
                },
                {
                  top: 310,
                  left: 290,
                  font:12,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
      
    ],
  };