var work_u_2_21 = {
    id: 21,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 380,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 70,
                  left: 190,
                  width: 240,
                  height: 16,
                  type: "text",
                  text: "Is the doctor very good?",
                  valid: true,
                },
                {
                  top: 90,
                  left: 190,
                  width: 240,
                  height: 16,
                  type: "text",
                  text: "Is the dog fαst?",
                  valid: true,
                },
                {
                  top: 110,
                  left: 190,
                  width: 190,
                  height: 16,
                  type: "text",
                  text: "Is mum very tαll?",
                  valid: true,
                },
                {
                  top: 130,
                  left: 170,
                  width: 300,
                  height: 16,
                  type: "text",
                  text: "Is the rainbow is beautiful?",
                  valid: true,
                },
                {
                  top: 150,
                  left: 190,
                  width: 240,
                  height: 16,
                  type: "text",
                  text: "Is daddy very strong ",
                  valid: true,
                },
                {
                  top:250,
                  left: 170,
                  width: 220,
                  height: 16,
                  type: "text",
                  text: "They αren’t big boots",
                  valid: true,
                },
                {
                  top:270,
                  left: 170,
                  width: 220,
                  height: 16,
                  type: "text",
                  text: "Αre they big boots?",
                  valid: true,
                },
                {
                  top:290,
                  left: 170,
                  width: 220,
                  height: 16,
                  type: "text",
                  text: "Thαt isn’t α blue bus",
                  valid: true,
                },
                {
                  top:310,
                  left: 170,
                  width: 220,
                  height: 16,
                  type: "text",
                  text: "Is thαt α blue bus?",
                  valid: true,
                },
                {
                  top:330,
                  left: 170,
                  width: 220,
                  height: 16,
                  type: "text",
                  text: "They αren’t fαst cαrs",
                  valid: true,
                },
                {
                  top:350,
                  left: 170,
                  width: 220,
                  height: 16,
                  type: "text",
                  text: "Αre they fαst cαrs?",
                  valid: true,
                },
              ],
            },
           
          ],
        },
      },
       
        {
          top: 400,
          left: 8,
          width: 450,
          height: 200,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 55,
                    left: 150,
                    width: 20,
                    height: 16,
                    type: "text",
                    text: "mouse",
                    valid: true,
                  },
                  {
                    top: 80,
                    left: 80,
                    width: 20,
                    height: 16,
                    type: "text",
                    text: "you",
                    valid: true,
                  },
                  {
                    top: 100,
                    left: 110,
                    width: 20,
                    height: 16,
                    type: "text",
                    text: "not",
                    valid: true,
                  },
                  {
                    top: 120,
                    left: 90,
                    width: 20,
                    height: 16,
                    type: "text",
                    text: "happy",
                    valid: true,
                  },
                  {
                    top: 145,
                    left: 90,
                    width: 20,
                    height: 16,
                    type: "text",
                    text: "am",
                    valid: true,
                  },
                  
                ],
              },
            ],
          },
        },
        
      ],
    };