var work_u_2_24 = {
    id: 24,
    
    paths: [
      {
      top: 15,
      left: 10,
      width: 450,
      height: 220,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 100,
                left: 230,
                width: 20,
                height: 16,
                type: "text",
                text: "Her",
                valid: true,
              },
              {
                top: 122,
                left: 250,
                width: 20,
                height: 16,
                type: "text",
                text: "Its",
                valid: true,
              },
              {
                top: 149,
                left: 250,
                width: 20,
                height: 16,
                type: "text",
                text: "His",
                valid: true,
              },
              {
                top: 170,
                left: 160,
                width: 20,
                height: 16,
                type: "text",
                text: "Your",
                valid: true,
              },
              {
                top: 170,
                left: 305,
                width: 20,
                height: 16,
                type: "text",
                text: "My",
                valid: true,
              },
              
            ],
          },
         
        ],
      },
    },
     
      {
        top: 250,
        left: 8,
        width: 450,
        height: 340,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 55,
                  left: 140,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "MY",
                  valid: true,
                },
                {
                  top: 85,
                  left: 135,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "His",
                  valid: true,
                },
                {
                  top: 115,
                  left: 135,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "Her",
                  valid: true,
                },
                {
                  top: 150,
                  left: 135,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "Its",
                  valid: true,
                },
                {
                  top: 255,
                  left: 75,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 275,
                  left: 80,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 295,
                  left: 65,
                  width: 20,
                  height: 16,
                  font:12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 234,
                  left: 215,
                  width: 20,
                  height: 16,
                  fontnt:5,
                  type: "text",
                  text: "Your",
                  valid: true,
                },
                {
                  top: 230,
                  left: 290,
                  width: 20,
                  height: 16,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 253,
                  left: 219,
                  width: 20,
                  height: 16,
                  font:5,
                  type: "text",
                  text: "His",
                  valid: true,
                },
                {
                  top: 250,
                  left: 290,
                  width: 20,
                  height: 16,
                  font:5,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 274,
                  left: 215,
                  width: 20,
                  height: 16,
                  fontnt:5,
                  type: "text",
                  text: "Her",
                  valid: true,
                },
                {
                  top: 274,
                  left: 290,
                  width: 20,
                  height: 16,
                  fontnt:5,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 294,
                  left: 215,
                  width: 20,
                  height: 16,
                  fontnt:5,
                  type: "text",
                  text: "Its",
                  valid: true,
                },
                {
                  top: 294,
                  left: 290,
                  width: 20,
                  height: 16,
                  fontnt:5,
                  type: "text",
                  text: "is",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
      
    ],
  };