var work_u_2_19 = {
  id: 19,
  paths: [
    {
      top: 15,
      left: 10,
      width: 450,
      height: 380,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 110,
                left: 210,
                width: 210,
                height: 16,
                font:13,
                type: "text",
                text: " Αsterisk isn’t strong",
                valid: true,
              },
              {
                top: 115,
                left: 395,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 100,
                left: 395,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 205,
                left: 0,
                width: 250,
                height: 20,
                font:10,
                type: "text",
                text: "Helen and Ann are'nt friends",
                valid: true,
              },
              {
                top: 195,
                left: 195,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 208,
                left: 198,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 206,
                left: 200,
                width: 250,
                height: 16,
                font:10,
                type: "text",
                text: "They αren’t red αnd yellow",
                valid: true,
              },
              {
                top: 195,
                left: 395,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 210,
                left: 395,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 290,
                left: 2,
                width: 240,
                height: 16,
                font:10,
                type: "text",
                text: "He isn't very young",
                valid: true,
              },
              {
                top: 283,
                left: 197,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 295,
                left: 195,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 360,
                left: 110,
                width: 240,
                height: 16,
                font:12,
                type: "text",
                text: "We αren’t tαll",
                valid: true,
              },
              {
                top: 347,
                left: 303,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 364,
                left: 305,
                width: 10,
                height: 10,
                area: {
                  top: 100,
                  left: 40,
                  width: 100,
                  height: 30,
                },

                type: "multiple",
                valid: true,
              },
            ],
          },
        ],
      },
    },

    {
      top: 400,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 85,
                left: 90,
                width: 20,
                height: 16,
                font:12,
                type: "text",
                text: " big",
                valid: true,
              },
              {
                top: 105,
                left: 80,
                width: 20,
                height: 16,
                font:12,
                type: "text",
                text: "isn't",
                valid: true,
              },
              {
                top: 125,
                left: 90,
                width: 20,
                height: 16,
                font:12,
                type: "text",
                text: "good",
                valid: true,
              },
              {
                top: 145,
                left: 90,
                width: 20,
                height: 16,
                font:12,
                type: "text",
                text: "are",
                valid: true,
              },
              
            ],
          },
        ],
      },
    },
  ],
};
