var apb_u_1_4 = {
  id: 4,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 85,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 85,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 140,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 115,
                left: 140,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 190,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 245,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 145,
                left: 90,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 145,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 145,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 145,
                left: 140,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 142,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 167,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 175,
                left: 245,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },

            ],
          },
        ],
      },
    },
    {
      top: 210,
      left: 8,
      width: 450,
      height: 117,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 20,
                left: 25,
                width: 70,
                height:140,
                type: "text",
                text: "d",
                valid: true,
              },
              
            ],
          },
        ],
      },
    },

    {
      top: 210,
      left: 8,
      width: 450,
      height: 117,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 50,
                left: 60,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 50,
                left: 175,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 50,
                left: 340,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 60,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 175,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 210,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 230,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 340,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 375,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
            ],
          },
        ],
      },
    },

    {
      top: 330,
      left: 8,
      width: 450,
      height: 260,
      zoom: {
        answers: [
          {
            paths: [
             
              {
                type: "underline",
                top: 138,
                left: 242,
                width: 119,
                rotate: 59,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 95,
                left: 258,
                width: 8,
                area: {
                    top: 95,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 1,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 157,
                left: 254,
                width: 139,
                rotate: 37,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 126,
                left: 258,
                width: 8,
                area: {
                    top: 126,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 2,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 155,
                left: 270,
                width: 90,
                rotate: 10,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 157,
                left: 258,
                width: 8,
                area: {
                    top: 157,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 3,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 131,
                left: 245,
                width: 160,
                rotate: -37,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 188,
                left: 258,
                width: 8,
                area: {
                    top: 188,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 4,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 140,
                left: 222,
                width: 162,
                rotate: -58,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 219,
                left: 258,
                width: 8,
                area: {
                    top: 219,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 5,
                type: "checkmark",
                valid: true
            },
             
            ],
          },
        ],
      },
    },
  ],
};
