var apb_u_1_4 = {
  id: 4,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 85,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 85,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 140,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 115,
                left: 140,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 190,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 245,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 145,
                left: 90,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 145,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 145,
                left: 115,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 145,
                left: 140,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 142,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 167,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 175,
                left: 245,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },

            ],
          },
        ],
      },
    },
    {
      top: 210,
      left: 8,
      width: 450,
      height: 117,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 20,
                left: 25,
                width: 70,
                height:140,
                type: "text",
                text: "d",
                valid: true,
              },
              
            ],
          },
        ],
      },
    },

    {
      top: 210,
      left: 8,
      width: 450,
      height: 117,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 50,
                left: 60,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 50,
                left: 175,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 50,
                left: 340,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 60,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 175,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 210,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 230,
                width: 16,
                height:16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 340,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 375,
                width: 16,
                height:16,
                type: "text",
                text: "b",
                valid: true,
              },
            ],
          },
        ],
      },
    },

    {
      top: 330,
      left: 8,
      width: 450,
      height: 260,
      zoom: {
        answers: [
          {
            paths: [
             
              {
                type: "underline",
                top: 158,
                left: 220,
                width: 119,
                rotate: 59,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 112,
                left: 244,
                width: 8,
                area: {
                    top: 112,
                    left: 244,
                    width: 8,
                    height: 8
                }, 
                underline: 1,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 182,
                left: 240,
                width: 165,
                rotate: 34,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 145,
                left: 244,
                width: 8,
                area: {
                    top: 145,
                    left: 244,
                    width: 8,
                    height: 8
                }, 
                underline: 2,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 160,
                left: 245,
                width: 145,
                rotate: -7,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 175,
                left: 244,
                width: 8,
                area: {
                    top: 175,
                    left: 244,
                    width: 8,
                    height: 8
                }, 
                underline: 3,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 144,
                left: 220,
                width: 200,
                rotate: -37,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 205,
                left: 244,
                width: 8,
                area: {
                    top: 205,
                    left: 244,
                    width: 8,
                    height: 8
                }, 
                underline: 4,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 155,
                left: 210,
                width: 210,
                rotate: 127,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 234,
                left: 244,
                width: 8,
                area: {
                    top: 234,
                    left: 244,
                    width: 8,
                    height: 8
                }, 
                underline: 5,
                type: "checkmark",
                valid: true
            },
             
            ],
          },
        ],
      },
    },
  ],
};
