var apb_u_1_5 = {
  id: 5,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 89,
                left: 160,
                width: 23,
                height: 16,
                type: "text",
                text: "C",
                valid: true,
              },
              {
                top: 89,
                left: 186,
                width: 23,
                height: 16,
                type: "text",
                text: "A",
                valid: true,
              },
              {
                top: 117,
                left: 160,
                width: 23,
                height: 16,
                type: "text",
                text: "B",
                valid: true,
              },
              {
                top: 117,
                left: 186,
                width: 23,
                height: 16,
                type: "text",
                text: "A",
                valid: true,
              },
              {
                top: 117,
                left: 238,
                width: 23,
                height: 16,
                type: "text",
                text: "A",
                valid: true,
              },
              {
                top: 117,
                left: 290,
                width: 23,
                height: 16,
                type: "text",
                text: "A",
                valid: true,
              },
              {
                top: 147,
                left: 160,
                width: 23,
                height: 16,
                type: "text",
                text: "A",
                valid: true,
              },
              {
                top: 175,
                left: 160,
                width: 23,
                height: 16,
                type: "text",
                text: "D",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 210,
      left: 8,
      width: 450,
      height: 140,
      zoom: {
        answers: [],
      },
    },
    {
      top: 350,
      left: 8,
      width: 450,
      height: 245,
      zoom: {
        answers: [],
      },
    },
  ],
};
