var apb_u_1_4 = {
  id: 4,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 85,
                left: 60,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 85,
                left: 112,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 137,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 60,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 112,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 115,
                left: 138,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 190,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 115,
                left: 242,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 145,
                left: 87,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 145,
                left: 112,
                width: 24,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 145,
                left: 138,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 60,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 139,
                width: 24,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 175,
                left: 164,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 175,
                left: 242,
                width: 24,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
            ],
          },
        ],
      },
    },

    {
      top: 210,
      left: 8,
      width: 450,
      height: 117,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 50,
                left: 60,
                width: 24,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 50,
                left: 172,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 50,
                left: 338,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 60,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 171,
                width: 24,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 207,
                width: 24,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 230,
                width: 24,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 85,
                left: 339,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 85,
                left: 373,
                width: 24,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
            ],
          },
        ],
      },
    },

    {
      top: 330,
      left: 8,
      width: 450,
      height: 260,
      zoom: {
        answers: [
          {
            paths: [
              {
                type: "underline",
                top: 158,
                left: 220,
                width: 119,
                rotate: 59,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 112,
                left: 244,
                width: 8,
                area: {
                  top: 112,
                  left: 244,
                  width: 8,
                  height: 8,
                },
                underline: 1,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 182,
                left: 240,
                width: 165,
                rotate: 34,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 145,
                left: 244,
                width: 8,
                area: {
                  top: 145,
                  left: 244,
                  width: 8,
                  height: 8,
                },
                underline: 2,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 160,
                left: 245,
                width: 145,
                rotate: -7,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 175,
                left: 244,
                width: 8,
                area: {
                  top: 175,
                  left: 244,
                  width: 8,
                  height: 8,
                },
                underline: 3,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 144,
                left: 220,
                width: 200,
                rotate: -37,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 205,
                left: 244,
                width: 8,
                area: {
                  top: 205,
                  left: 244,
                  width: 8,
                  height: 8,
                },
                underline: 4,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 155,
                left: 210,
                width: 210,
                rotate: 127,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 234,
                left: 244,
                width: 8,
                area: {
                  top: 234,
                  left: 244,
                  width: 8,
                  height: 8,
                },
                underline: 5,
                type: "checkmark",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
