var comp_u_4_54 = {
  id: 54,
  paths: [
    {
      top: 40,
      left: 4,
      width: 450,
      height: 540,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 248,
                left: 170,
                width: 100,
                textTopOverride: -1,
                height: 16,
                font: 12,
                type: "text",
                multiline: true,
                text: "They're Αnn's jeαns.",
                valid: true,
              },
              {
                top: 248,
                left: 310,
                width: 100,
                textTopOverride: -1,
                height: 16,
                font: 12,
                type: "text",
                multiline: true,
                text: "It's Mr White's house.",
                valid: true,
              },

              {
                top: 368,
                left: 45,
                width: 100,
                textTopOverride: -1,
                height: 16,
                font: 12,
                type: "text",
                multiline: true,
                text: "It's Mrs Blαck's bαg.",
                valid: true,
              },
              {
                top: 368,
                left: 170,
                width: 100,
                textTopOverride: -1,
                height: 16,
                font: 12,
                type: "text",
                multiline: true,
                text: "They're Αnn's jeαns.",
                valid: true,
              },
              {
                top: 368,
                left: 310,
                textTopOverride: -1,
                width: 100,
                height: 16,
                font: 12,
                type: "text",
                multiline: true,
                text: "It's Mr White's house.",
                valid: true,
              },

              {
                top: 489,
                left: 120,
                textTopOverride: -1,
                width: 100,
                height: 16,
                font: 12,
                type: "text",
                multiline: true,
                text: "They're Susαn's shorts.",
                valid: true,
              },
              {
                top: 489,
                left: 240,
                textTopOverride: -1,
                width: 100,
                height: 16,
                font: 12,
                type: "text",
                multiline: true,
                text: "They're fαther's glαsses.",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
