var comp_u_4_51 = {
  id: 51,
  paths: [
    {
      top: 25,
      left: 4,
      width: 450,
      height: 250,
    },
  
    {
      top: 280,
      left: 4,
      width: 450,
      height: 310,
      zoom: {
        answers: [
          {
            paths: [ 

              {
                top: 48,
                left: 200,
                width: 60,
                textTopOverride:-1,
                height: 16,
                font: 12,
                type: "text",
                text: "he",
                valid: true,
              },  
                  {
                    top: 49,
                    left: 290,
                    width: 60,
                    textTopOverride:-1,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "him",
                    valid: true,
                  },
                  {
                    top: 69,
                    left: 200,
                    width: 60,
                    height: 16,
                    textTopOverride:-1,
                    font: 12,
                    type: "text",
                    text: "they",
                    valid: true,
                  },  
                      {
                        top: 69,
                        left: 290,
                        textTopOverride:-1,
                        width: 60,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "them",
                        valid: true,
                      },
                      {
                        top: 91,
                        left: 200,
                        width: 60,
                        height: 16,
                        textTopOverride:-1,
                        font: 12,
                        type: "text",
                        text: "we",
                        valid: true,
                      },  
                          {
                            top: 91,
                            left: 290,
                            width: 60,
                            textTopOverride:-1,
                            height: 16,
                            font: 12,
                            type: "text",
                            text: "us",
                            valid: true,
                          },
                    

                          {
                            top: 113,
                            left: 200,
                            width: 60,
                            height: 16,
                            textTopOverride:-1,
                            font: 12,
                            type: "text",
                            text: "you",
                            valid: true,
                          },  
                              {
                                top: 113,
                                left: 290,
                                textTopOverride:-1,
                                width: 60,
                                height: 16,
                                font: 12,
                                type: "text",
                                text: "you",
                                valid: true,
                              },

                              {
                                top: 135,
                                left: 200,
                                textTopOverride:-1,
                                width: 60,
                                height: 16,
                                font: 12,
                                type: "text",
                                text: "it",
                                valid: true,
                              },  
                                  {
                                    top: 135,
                                    left: 290,
                                    textTopOverride:-1,
                                    width: 60,
                                    height: 16,
                                    font: 12,
                                    type: "text",
                                    text: "it",
                                    valid: true,
                                  },

                                  {
                                    top: 268,
                                    left: 150,
                                    width: 55,
                                    textTopOverride:-1,
                                    height: 16,
                                    font: 12,
                                    type: "text",
                                    text: "ummer",
                                    valid: true,
                                  },  
                                  
                                  {
                                    top: 268,
                                    left: 247,
                                    textTopOverride:-1,
                                    width: 55,
                                    height: 16,
                                    font: 12,
                                    type: "text",
                                    text: "utumn",
                                    valid: true,
                                  },  
                                  {
                                    top: 268,
                                    left: 345,
                                    textTopOverride:-1,
                                    width: 55,
                                    height: 16,
                                    font: 12,
                                    type: "text",
                                    text: "inter",
                                    valid: true,
                                  },  
                         
            ],
          },
        ],
      },
    },
  ],
};
