var comp_u_4_71 = {
  id: 71,
  paths: [
    {
      top: 40,
      left: 8,
      width: 450,
      height: 540,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 136,
                left: 310,
                textTopOverride: -1,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "June",
                valid: true,
              },

              {
                top: 158,
                left: 40,
                textTopOverride: -1,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "January",
                valid: true,
              },
              {
                top: 179,
                left: 40,
                textTopOverride: -1,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "February",
                valid: true,
              },
              {
                top: 158,
                left: 310,
                textTopOverride: -1,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "July",
                valid: true,
              },
              {
                top: 179,
                left: 310,
                textTopOverride: -1,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "August",
                valid: true,
              },
              {
                top: 308,
                left: 225,
                width: 80,
                height: 16,
                font: 12,
                type: "text",
                text: "Summer",
                valid: true,
              },
              {
                top: 329,
                left: 225,
                width: 80,
                height: 16,
                font: 12,
                type: "text",
                text: "Autumn",
                valid: true,
              },
              {
                top: 329,
                left: 140,
                width: 80,
                height: 16,
                font: 12,
                type: "text",
                text: "Spring",
                valid: true,
              },
              {
                top: 466,
                textTopOverride: -1,
                left: 40,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "March",
                valid: true,
              },

              {
                top: 466,
                textTopOverride: -1,
                left: 310,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "September",
                valid: true,
              },
              {
                top: 489,
                left: 40,
                textTopOverride: -1,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "April",
                valid: true,
              },
              {
                top: 489,
                left: 310,
                width: 90,
                textTopOverride: -1,
                height: 16,
                font: 12,
                type: "text",
                text: "October",
                valid: true,
              },
              {
                top: 509,
                textTopOverride: -1,
                left: 40,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "May",
                valid: true,
              },
              {
                top: 509,
                left: 310,
                textTopOverride: -1,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "November",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
