var work_u_5_100= {
    id: 100,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 420,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 122,
                  left: 315,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "worked",
                  valid: true,
                },
                {
                  top: 142,
                  left: 125,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "watched",
                  valid: true,
                },
                {
                  top: 142,
                  left: 315,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "liked",
                  valid: true,
                },
                {
                  top: 161,
                  left: 125,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "washed",
                  valid: true,
                },
                {
                  top: 161,
                  left: 315,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "danced",
                  valid: true,
                },
                {
                  top: 181,
                  left: 115,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "lived",
                  valid: true,
                },
                {
                  top: 181,
                  left: 315,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "stayed",
                  valid: true,
                },
                {
                  top: 265,
                  left: 250,
                  width: 150,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "he danced at the party?",
                  valid: true,
                },
                {
                  top: 290,
                  left: 235,
                  width: 180,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "He didn't dance at the party",
                  valid: true,
                },
                {
                  top: 332,
                  left: 240,
                  width: 180,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "closed the door",
                  valid: true,
                },
                {
                  top: 332,
                  left: 60,
                  width: 180,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Phoned Mary",
                  valid: true,
                },
                {
                  top: 352,
                  left: 240,
                  width: 180,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Did they close  the door?",
                  valid: true,
                },
                {
                  top: 372,
                  left: 40,
                  width: 180,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "You didn't phone Mary",
                  valid: true,
                },
              ],
            },
          ],   
        },
      },
       
        {
          top: 420,
          left: 8,
          width: 450,
          height: 360,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 70,
                    left: 250,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "he did.",
                    valid: true,
                  },
                  {
                    top: 70,
                    left: 320,
                    width: 80,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "he didn't.",
                    valid: true,
                  },
                  {
                    top: 93,
                    left: 230,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Yes, it did.",
                    valid: true,
                  },
                  {
                    top: 93,
                    left: 300,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, it didn't.",
                    valid: true,
                  },
                  {
                    top: 113,
                    left: 200,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Yes, She did.",
                    valid: true,
                  },
                  {
                    top: 113,
                    left: 280,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, She didn't.",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };