var apb_u_6_23 = {
  id: 23,
  paths: [
    {
      top: 220,
      left: 8,
      width: 450,
      height: 370,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 45,
                left: 325,
                width: 25,
				height:25,
                type: "text",
                text: "yellow",
                valid: true,
              },
              {
                top: 100,
                left: 100,
                width: 25,
                type: "text",
                height: 25,
                text: "zebra",
                valid: true,
              },
              {
                top: 180,
                left: 315,
                width: 25,
                type: "text",
                height: 25,
                text: "zoo",
                valid: true,
              },
              {
                top: 230,
                left: 110,
                width: 25,
                type: "text",
                height: 25,
                text: "fox",
                valid: true,
              },
              {
                top: 317,
                left: 320,
                width: 25,
                type: "text",
                height: 25,
                text: "baby",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 95,
                left: 245,
                width: 25,
                height: 25,
                type: "text",
                text: "daddy",
                valid: true,
              },
              {
                top: 115,
                left: 245,
                width: 25,
                height: 25,
                type: "text",
                text: "glass",
                valid: true,
              },
              {
                top: 138,
                left: 250,
                width: 25,
                height: 25,
                type: "text",
                text: "hat",
                valid: true,
              },
              {
                top: 55,
                left: 360,
                width: 25,
                height: 25,
                type: "text",
                text: "lemon",
                valid: true,
              },
              {
                top: 75,
                left: 360,
                width: 25,
                height: 25,
                type: "text",
                text: "orange",
                valid: true,
              },
              {
                top: 95,
                left: 370,
                width: 25,
                height: 25,
                type: "text",
                text: "tree",
                valid: true,
              },
              {
                top: 115,
                left: 370,
                width: 25,
                height: 25,
                type: "text",
                text: "van",
                valid: true,
              },
              {
                top: 135,
                left: 370,
                width: 25,
                height: 25,
                type: "text",
                text: "zebra",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
