var apb_u_6_23 = {
  id: 23,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 105,
                left: 251,
                width: 35,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "daddy",
                valid: true,
              },
              {
                top: 125,
                left: 251,
                width: 35,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "glass",
                valid: true,
              },
              {
                top: 146,
                left: 250,
                width: 35,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "hat",
                valid: true,
              },
              {
                top: 66,
                left: 370,
                width: 35,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "lemon",
                valid: true,
              },
              {
                top: 85,
                left: 370,
                width: 35,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "orange",
                valid: true,
              },
              {
                top: 105,
                left: 370,
                width: 35,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "tree",
                valid: true,
              },
              {
                top: 126,
                left: 370,
                width: 25,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "van",
                valid: true,
              },
              {
                top: 147,
                left: 370,
                width: 35,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "zebra",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 220,
      left: 8,
      width: 450,
      height: 370,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 59,
                left: 315,
                width: 100,
                height: 25,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "yellow",
                valid: true,
              },
              {
                top: 113,
                left: 90,
                width: 100,
                font: 17,
                textTopOverride: -10,
                type: "text",
                height: 25,
                text: "zebra",
                valid: true,
              },
              {
                top: 190,
                left: 310,
                width: 100,
                font: 17,
                textTopOverride: -10,
                type: "text",
                height: 25,
                text: "zoo",
                valid: true,
              },
              {
                top: 240,
                left: 100,
                width: 100,
                type: "text",
                font: 17,
                textTopOverride: -7,
                height: 25,
                text: "fox",
                valid: true,
              },
              {
                top: 330,
                left: 320,
                width: 100,
                font: 17,
                textTopOverride: -10,
                type: "text",
                height: 25,
                text: "baby",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
