var apb_u_6_24 = {
  id: 24,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 250,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 68,
                left: 40,
                width: 120,
                font: 17,
                textTopOverride: 1,
                height: 20,
                type: "text",
                text: "thank you",
                valid: true,
              },
              {
                top: 110,
                left: 270,
                width: 120,
                height: 20,
                font: 17,
                textTopOverride: -5,
                type: "text",
                text: "BABY ZEBRA",
                valid: true,
              },
              {
                top: 150,
                left: 40,
                width: 80,
                height: 20,
                type: "text",
                font: 17,
                textTopOverride: -10,
                text: "a fox",
                valid: true,
              },
              {
                top: 180,
                left: 270,
                width: 100,
                height: 30,
                font: 17,
                textTopOverride: -10,
                type: "text",
                text: "A BOX",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 260,
      left: 8,
      width: 450,
      height: 330,
      zoom: {
        answers: [
          {
            paths: [
              {
                type: "underline",
                top: 95,
                left: 270,
                width: 100,
                rotate: 210,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 44,
                left: 208,
                width: 82,
                area: {
                  top: 44,
                  left: 208,
                  width: 82,
                  height: 45,
                },
                underline: 1,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 165,
                left: 260,
                width: 110,
                rotate: 210,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 100,
                left: 208,
                width: 82,
                area: {
                  top: 100,
                  left: 208,
                  width: 82,
                  height: 45,
                },
                underline: 2,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 230,
                left: 245,
                width: 140,
                rotate: 220,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 150,
                left: 208,
                width: 82,
                area: {
                  top: 150,
                  left: 208,
                  width: 82,
                  height: 45,
                },
                underline: 3,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 180,
                left: 180,
                width: 250,
                rotate: 120,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 265,
                left: 208,
                width: 82,
                area: {
                  top: 265,
                  left: 208,
                  width: 82,
                  height: 45,
                },
                underline: 4,
                type: "checkmark",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
