var comp_u_3_41 = {
  id: 41,
  paths: [
    {
      top: 40,
      left: 8,
      width: 450,
      height: 210,
      zoom: {
        answers: [],
      },
    },
    {
      top: 235,
      left: 8,
      width: 450,
      height: 200,
      zoom: {
        answers: [],
      },
    },
    {
      top: 440,
      left: 8,
      width: 450,
      height: 161,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 70,
                left: 60,
                width: 120,
                height: 16,
                textTopOverride: 1,
                font: 12,
                type: "text",
                text: "tigers",
                valid: true,
              },
              {
                top: 70,
                left: 180,
                width: 115,
                textTopOverride: 1,
                height: 16,
                font: 12,
                type: "text",
                text: "boxes",
                valid: true,
              },
              {
                top: 70,
                left: 300,
                width: 110,
                height: 16,
                font: 12,
                type: "text",
                text: "puppies",
                valid: true,
              },

              {
                top: 88,
                left: 60,
                width: 120,
                height: 16,
                textTopOverride: 1,
                font: 12,
                type: "text",
                text: "aeroplanes",
                valid: true,
              },
              {
                top: 90,
                left: 180,
                width: 115,
                height: 16,
                textTopOverride: 1,
                font: 12,
                type: "text",
                text: "buses",
                valid: true,
              },
              {
                top: 90,
                left: 300,
                width: 110,
                textTopOverride: 1,
                height: 16,
                font: 12,
                type: "text",
                text: "daisies",
                valid: true,
              },

              {
                top: 105,
                left: 60,
                width: 120,
                height: 16,
                font: 12,
                textTopOverride: 1,
                type: "text",
                text: "boys",
                valid: true,
              },
              {
                top: 105,
                left: 180,
                width: 115,
                textTopOverride: 1,
                height: 16,
                font: 12,
                type: "text",
                text: "Kisses",
                valid: true,
              },

              {
                top: 105,
                left: 300,
                width: 110,
                textTopOverride: 1,
                height: 16,
                font: 12,
                type: "text",
                text: "ladies",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
