var apb_u_5_20 = {
  id: 20,
  paths: [
    {
      top: 340,
      left: 8,
      width: 450,
      height: 250,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 70,
                left: 217,
                width: 20,
                height: 20,
                type: "text",
                text: "w",
                valid: true,
              },
              {
                top: 70,
                left: 244,
                width: 20,
                height: 20,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 70,
                left: 269,
                width: 20,
                height: 20,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 70,
                left: 296,
                width: 20,
                height: 20,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 70,
                left: 320,
                width: 20,
                height: 20,
                type: "text",
                text: "o",
                valid: true,
              },
              {
                top: 70,
                left: 345,
                width: 20,
                height: 20,
                type: "text",
                text: "w",
                valid: true,
              },
              {
                top: 100,
                left: 217,
                width: 20,
                height: 20,
                type: "text",
                text: "u",
                valid: true,
              },
              {
                top: 100,
                left: 244,
                width: 20,
                height: 20,
                type: "text",
                text: "m",
                valid: true,
              },
              {
                top: 100,
                left: 268,
                width: 20,
                height: 20,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 100,
                left: 296,
                width: 20,
                height: 20,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 100,
                left: 320,
                width: 20,
                height: 20,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 100,
                left: 345,
                width: 20,
                height: 20,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 372,
                width: 20,
                height: 20,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 394,
                width: 20,
                height: 20,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 130,
                left: 220,
                width: 20,
                height: 20,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 130,
                left: 240,
                width: 20,
                height: 20,
                type: "text",
                text: "u",
                valid: true,
              },
              {
                top: 130,
                left: 265,
                width: 20,
                height: 20,
                type: "text",
                text: "s",
                valid: true,
              },
              {
                top: 160,
                left: 220,
                width: 20,
                height: 20,
                type: "text",
                text: "w",
                valid: true,
              },
              {
                top: 160,
                left: 245,
                width: 20,
                height: 20,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 160,
                left: 269,
                width: 20,
                height: 20,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 160,
                left: 296,
                width: 20,
                height: 20,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 190,
                left: 220,
                width: 20,
                height: 20,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 190,
                left: 245,
                width: 20,
                height: 20,
                type: "text",
                text: "o",
                valid: true,
              },
              {
                top: 190,
                left: 269,
                width: 20,
                height: 20,
                type: "text",
                text: "s",
                valid: true,
              },
              {
                top: 190,
                left: 296,
                width: 20,
                height: 20,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 220,
                left: 220,
                width: 20,
                height: 20,
                type: "text",
                text: "t",
                valid: true,
              },
              {
                top: 220,
                left: 245,
                width: 20,
                height: 20,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 220,
                left: 269,
                width: 20,
                height: 20,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 220,
                left: 296,
                width: 20,
                height: 20,
                type: "text",
                text: "e",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 8,
      width: 450,
      height: 317,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 82,
                left: 128,
                width: 24,
                height: 24,
                type: "text",
                text: "cat",
                valid: true,
              },
              {
                top: 148,
                left: 128,
                width: 24,
                height: 24,
                type: "text",
                text: "van",
                valid: true,
              },
              {
                top: 215,
                left: 129,
                width: 24,
                height: 24,
                type: "text",
                text: "rose",
                valid: true,
              },
              {
                top: 280,
                left: 129,
                width: 24,
                height: 24,
                type: "text",
                text: "tree",
                valid: true,
              },
              {
                top: 80,
                left: 342,
                width: 25,
                height: 25,
                type: "text",
                text: "cup",
                valid: true,
              },
              {
                top: 148,
                left: 342,
                width: 28,
                height: 28,
                type: "text",
                text: "bus",
                valid: true,
              },
              {
                top: 215,
                left: 342,
                width: 24,
                height: 24,
                type: "text",
                text: "hen",
                valid: true,
              },
              {
                top: 280,
                left: 342,
                width: 24,
                height: 24,
                type: "text",
                text: "star",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
