var apb_u_5_21 = {
  id: 21,
  paths: [
    {
      top: 310,
      left: 8,
      width: 450,
      height: 280,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 82,
                left: 38,
                width: 18,
                height: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 82,
                left: 130,
                width: 18,
                height: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 82,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 114,
                left: 38,
                width: 18,
                height: 18,
                type: "text",
                text: "w",
                valid: true,
              },
              {
                top: 114,
                left: 130,
                width: 18,
                height: 18,
                type: "text",
                text: "w",
                valid: true,
              },
              {
                top: 114,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                text: "w",
                valid: true,
              },
              {
                top: 146,
                left: 45,
                width: 18,
                height: 18,
                type: "text",
                text: "t",
                valid: true,
              },
              {
                top: 146,
                left: 130,
                width: 18,
                height: 18,
                type: "text",
                text: "t",
                valid: true,
              },
              {
                top: 146,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                text: "t",
                valid: true,
              },
              {
                top: 175,
                left: 38,
                width: 18,
                height: 18,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 175,
                left: 130,
                width: 18,
                height: 18,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 175,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 208,
                left: 45,
                width: 18,
                height: 18,
                type: "text",
                text: "u",
                valid: true,
              },
              {
                top: 208,
                left: 130,
                width: 18,
                height: 18,
                type: "text",
                text: "u",
                valid: true,
              },
              {
                top: 208,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                text: "u",
                valid: true,
              },
              {
                top: 239,
                left: 50,
                width: 18,
                height: 18,
                type: "text",
                text: "s",
                valid: true,
              },
              {
                top: 238,
                left: 132,
                width: 18,
                height: 18,
                type: "text",
                text: "s",
                valid: true,
              },
              {
                top: 235,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                text: "s",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 8,
      width: 450,
      height: 290,
      zoom: {
        answers: [
          {
						paths: [
							{
								top: 85,
								left: 75,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid: true
							},
              {
								top: 115,
								left: 190,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid: true
							},
              {
								top: 142,
								left: 70,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid: true
							},
              {
								top: 172,
								left: 195,
								width: 35,
                height:35,
								type: "text",
								text: "_____",
								valid: true
							},
              {
								top: 200,
								left: 76,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: true
							},
              {
								top: 235,
								left: 200,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid: true
							},
						],
					},
        ],
      },
    },
  ],
};
