var apb_u_5_21 = {
  id: 21,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 290,
      zoom: {
        answers: [
          {
						paths: [
							{
								top: 95,
								left: 75,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: true
							},
              {
								top: 95,
								left: 190,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "__",
								valid:false
							},
              {
								top: 95,
								left: 310,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid:false
							},
              {
								top: 125,
								left: 196,
								width: 35,
                height:35,
								type: "text",
                textTopOverride:-12,
								text: "___",
								valid: true
							},
              {
								top: 125,
								left:80 ,
								width: 35,
                height:35,
								type: "text",
                textTopOverride:-12,
								text: "____",
								valid: false
							},
              {
								top: 125,
								left:300 ,
								width: 35,
                height:35,
								type: "text",
                textTopOverride:-12,
								text: "____",
								valid: false
							},

              {
								top: 153,
								left: 70,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "__",
								valid: true
							},
              {
								top: 153,
								left: 200,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "__",
								valid: false
							},
              {
								top: 153,
								left: 306,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "__",
								valid: false
							},

              {
								top: 184,
								left: 200,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid: false
							},
              {
								top: 184,
								left: 80,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: false
							},
              {
								top: 184,
								left: 305,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: true
							},
              {
								top: 210,
								left: 76,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: true
							},
              {
								top: 210,
								left: 190,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: false
							},
              {
								top: 210,
								left: 300,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: false
							},
              {
								top: 246,
								left: 200,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "___",
								valid: true
							},
              {
								top: 245,
								left: 310,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid: false
							},
              {
								top: 245,
								left: 75,
                textTopOverride:-12,
								width: 35,
                height:35,
								type: "text",
								text: "____",
								valid: false
							},
						],
					},
        ],
      },
    },
    {
      top: 310,
      left: 8,
      width: 450,
      height: 280,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 82,
                left: 38,
                width: 18,
                font:20,
                height: 18,
                
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 82,
                left: 130,
                width: 18,
                height: 18,
                font:20,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 82,
                left: 315,
                width: 18,
                font:20,
                height: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 114,
                left: 38,
                width: 18,
                height: 18,
                type: "text",
                text: "w",
                font:20,
                valid: true,
              },
              {
                top: 114,
                left: 130,
                width: 18,
                height: 18,
                type: "text",
                text: "w",
                font:20,
                valid: true,
              },
              {
                top: 114,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                font:20,
                text: "w",
                valid: true,
              },
              {
                top: 146,
                left: 45,
                width: 18,
                height: 18,
                type: "text",
                text: "t",
                font:20,
                valid: true,
              },
              {
                top: 146,
                left: 130,
                width: 18,
                height: 18,
                type: "text",
                text: "t",
                font:20,
                valid: true,
              },
              {
                top: 146,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                font:20,
                text: "t",
                valid: true,
              },
              {
                top: 178,
                left: 38,
                width: 18,
                font:20,
                height: 18,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 178,
                left: 130,
                width: 18,
                font:20,
                height: 18,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 175,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                text: "b",
                font:20,
                valid: true,
              },
              {
                top: 208,
                left: 45,
                width: 18,
                height: 18,
                type: "text",
                text: "u",
                font:20,
                valid: true,
              },
              {
                top: 208,
                left: 130,
                width: 18,
                height: 18,
                font:20,
                type: "text",
                text: "u",
                valid: true,
              },
              {
                top: 208,
                left: 315,
                width: 18,
                height: 18,
                type: "text",
                font:20,
                text: "u",
                valid: true,
              },
              {
                top: 240,
                left: 50,
                width: 18,
                height: 18,
                type: "text",
                text: "s",
                font:20,
                valid: true,
              },
              {
                top: 240,
                left: 132,
                width: 18,
                height: 18,
                type: "text",
                font:20,
                text: "s",
                valid: true,
              },
              {
                top: 240,
                left: 315,
                width: 18,
                font:20,
                height: 18,
                type: "text",
                text: "s",
                valid: true,
              },
            ],
          },
        ],
      },
    },

  ],
};
