var apb_u_5_20 = {
  id: 20,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 317,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 90,
                left: 123,
                width: 60,
                height: 24,
                font: 15,
                type: "text",
                text: "cat",
                valid: true,
                textTopOverride: -4,
              },
              {
                top: 157,
                left: 123,
                width: 60,
                height: 24,
                font: 15,
                type: "text",
                text: "van",
                valid: true,
                textTopOverride: -4,
              },
              {
                top: 224,
                left: 123,
                width: 60,
                height: 24,
                font: 15,
                type: "text",
                text: "rose",
                valid: true,
                textTopOverride: -4,
              },
              {
                top: 289,
                left: 123,
                width: 60,
                font: 15,
                height: 24,
                type: "text",
                text: "tree",
                valid: true,
                textTopOverride: -4,
              },
              {
                top: 90,
                left: 337,
                width: 60,
                height: 25,
                font: 15,
                type: "text",
                text: "cup",
                valid: true,
                textTopOverride: -4,
              },
              {
                top: 157,
                left: 337,
                width: 60,
                height: 28,
                font: 15,
                type: "text",
                text: "bus",
                valid: true,
                textTopOverride: -4,
              },
              {
                top: 224,
                left: 337,
                width: 60,
                height: 24,
                font: 15,
                type: "text",
                text: "hen",
                valid: true,
                textTopOverride: -4,
              },
              {
                top: 289,
                left: 337,
                width: 60,
                height: 24,
                font: 15,
                type: "text",
                text: "star",
                valid: true,
                textTopOverride: -4,
              },
            ],
          },
        ],
      },
    },
    {
      top: 340,
      left: 8,
      width: 450,
      height: 250,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 77,
                left: 215,
                width: 25,
                height: 25,
                textTopOverride: -6,
                type: "text",
                font: 20,
                text: "W",
                valid: true,
              },
              {
                top: 81,
                left: 240,
                font: 20,
                textTopOverride: -10,
                width: 25,
                height: 25,
                type: "text",
                text: "I",
                valid: true,
              },
              {
                top: 81,
                left: 269,
                width: 25,
                textTopOverride: -10,
                font: 20,
                height: 25,
                type: "text",
                text: "N",
                valid: true,
              },
              {
                top: 81,
                left: 293,
                textTopOverride: -10,
                width: 25,
                height: 25,
                font: 20,
                type: "text",
                text: "D",
                valid: true,
              },
              {
                top: 81,
                left: 317,
                width: 25,
                textTopOverride: -10,
                height: 25,
                font: 20,
                type: "text",
                text: "O",
                valid: true,
              },
              {
                top: 81,
                left: 342,
                textTopOverride: -10,
                font: 20,
                width: 25,
                height: 25,
                type: "text",
                text: "W",
                valid: true,
              },
              {
                top: 112,
                left: 217,
                textTopOverride: -10,
                font: 20,
                width: 20,
                height: 20,
                type: "text",
                text: "U",
                valid: true,
              },
              {
                top: 112,
                left: 244,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "M",
                valid: true,
              },
              {
                top: 112,
                left: 268,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "B",
                valid: true,
              },
              {
                top: 112,
                left: 296,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "R",
                valid: true,
              },
              {
                top: 112,
                left: 320,
                width: 20,
                height: 20,
                textTopOverride: -10,
                font: 20,
                type: "text",
                text: "E",
                valid: true,
              },
              {
                top: 112,
                left: 345,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "L",
                valid: true,
              },
              {
                top: 112,
                left: 372,
                width: 20,
                height: 20,
                textTopOverride: -10,
                font: 20,
                type: "text",
                text: "L",
                valid: true,
              },
              {
                top: 112,
                left: 394,
                width: 20,
                height: 20,
                textTopOverride: -10,
                font: 20,
                type: "text",
                text: "A",
                valid: true,
              },
              {
                top: 141,
                left: 218,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "B",
                valid: true,
              },
              {
                top: 141,
                left: 242,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "U",
                valid: true,
              },
              {
                top: 141,
                left: 266,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "S",
                valid: true,
              },
              {
                top: 171,
                left: 216,
                width: 20,
                textTopOverride: -10,
                font: 20,

                height: 20,
                type: "text",
                text: "W",
                valid: true,
              },
              {
                top: 171,
                left: 245,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "A",
                valid: true,
              },
              {
                top: 171,
                left: 269,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "L",
                valid: true,
              },
              {
                top: 171,
                left: 296,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "L",
                valid: true,
              },
              {
                top: 200,
                left: 216,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "R",
                valid: true,
              },
              {
                top: 200,
                left: 245,
                textTopOverride: -10,
                font: 20,
                width: 20,
                height: 20,
                type: "text",
                text: "O",
                valid: true,
              },
              {
                top: 200,
                left: 269,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "S",
                valid: true,
              },
              {
                top: 200,
                left: 296,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "E",
                valid: true,
              },
              {
                top: 230,
                left: 216,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "T",
                valid: true,
              },
              {
                top: 230,
                left: 242,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "R",
                valid: true,
              },
              {
                top: 230,
                left: 269,
                width: 20,
                textTopOverride: -10,
                font: 20,
                height: 20,
                type: "text",
                text: "E",
                valid: true,
              },
              {
                top: 230,
                left: 296,
                textTopOverride: -10,
                font: 20,
                width: 20,
                height: 20,
                type: "text",
                text: "E",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
