var apb_u_7_28 = {
  id: 28,
  paths: [
    {
      top: 330,
      left: 8,
      width: 450,
      height: 270,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 20,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 50,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 75,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 160,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "j",
                valid: true,
              },
              {
                top: 190,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "k",
                valid: true,
              },
              {
                top: 210,
                left:130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 12,
                left: 353,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "s",
                valid: true,
              },
              {
                top: 33,
                left: 353,
                width: 20,
                height: 20,
                type: "text",
                font:20,
                text: "t",
                valid: true,
              },
              {
                top: 60,
                left: 353,
                font:20,
                width: 20,
                height: 20,
                type: "text",
                text: "u",
                valid: true,
              },
              {
                top: 80,
                left: 353,
                width: 20,
                font:20,
                height: 20,
                type: "text",
                text: "v",
                valid: true,
              },
              {
                top: 140,
                left: 353,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "w",
                valid: true,
              },
              {
                top: 163,
                left: 388,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "x",
                valid: true,
              },
              {
                top: 185,
                left: 353,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "y",
                valid: true,
              },
              {
                top: 210,
                left: 353,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "z",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 8,
      width: 450,
      height: 317,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 115,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 140,
                left: 130,
                width: 20,
                height: 20,
                type: "text",
                font:20,
                text: "c",
                valid: true,
              },
              {
                top: 215,
                left: 130,
                width: 20,
                height: 20,
                type: "text",
                font:20,
                text: "d",
                valid: true,
              },
              {
                top: 240,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 267,
                left: 130,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "f",
                valid: true,
              },
              {
                top: 90,
                left: 353,
                width: 20,
                height: 20,
                type: "text",
                font:20,
                text: "m",
                valid: true,
              },
              {
                top: 118,
                left: 353,
                width: 20,
                height: 20,
                type: "text",
                font:20,
                text: "n",
                valid: true,
              },
              {
                top: 140,
                left: 353,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "o",
                valid: true,
              },
              {
                top: 215,
                left: 353,
                width: 20,
                height: 20,
                type: "text",
                font:20,
                text: "p",
                valid: true,
              },
              {
                top: 240,
                left: 353,
                width: 20,
                height: 20,
                font:20,
                type: "text",
                text: "q",
                valid: true,
              },
              {
                top: 267,
                left: 353,
                width: 20,
                height: 20,
                type: "text",
                text: "r",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
