var apb_u_7_29 = {
  id: 29,
  paths: [
    {
      top: 195,
      left: 8,
      width: 450,
      height: 400,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 95,
                left: 293,
                height: 18,
                width: 18,
                font:16,
                type: "text",
                textTopOverride:2,
                text: "l",
                valid: true,
              },
              {
                top: 95,
                left: 365,
                height: 18,
                width: 18,
                font:16,
                type: "text",
                textTopOverride:2,
                text: "l",
                valid: true,
              },
              {
                top: 95,
                left: 405,
                height: 18,
                width: 18,
                font:16,
                textTopOverride:2,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 122,
                left: 256,
                height: 20,
                textTopOverride:2,
                width: 18,
                font:16,
                type: "text",
                text: "p",
                valid: true,
              },
              {
                top: 122,
                left: 357,
                height: 20,
                width: 18,
                textTopOverride:2,
                font:16,
                type: "text",
                text: "p",
                valid: true,
              },
              {
                top: 122,
                left: 408,
                height: 20,
                textTopOverride:2,
                width: 18,
                font:16,
                type: "text",
                text: "p",
                valid: true,
              },
              {
                top: 157,
                left: 256,
                height: 20,
                textTopOverride:2,
                font:16,
                width: 18,
                type: "text",
                text: "h",
                valid: true,
                
              },
              {
                top: 157,
                left: 338,
                height: 20,
                textTopOverride:2,
                font:16,
                width: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 157,
                left: 405,
                height: 20,
                textTopOverride:2,
                font:16,
                width: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 195,
                left: 278,
                textTopOverride:2,
                font:16,
                height: 20,
                width: 18,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 195,
                left: 360,
                height: 20,
                textTopOverride:2,
                font:16,
                width: 18,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 195,
                left: 400,
                height: 20,
                font:16,
                width: 18,
                textTopOverride:2,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 229,
                left: 267,
                font:16,
                height: 20,
                width: 18,
                textTopOverride:2,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 229,
                left: 338,
                height: 20,
                font:16,
                width: 18,
                textTopOverride:2,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 229,
                left: 405,
                textTopOverride:2,
                height: 20,
                font:16,
                width: 18,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 259,
                textTopOverride:2,
                left: 278,
                height: 20,
                width: 18,
                font:16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 259,
                left: 348,
                textTopOverride:2,
                height: 20,
                width: 18,
                font:16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 259,
                left: 405,
                textTopOverride:2,
                height: 20,
                width: 18,
                font:16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 290,
                left: 278,
                textTopOverride:2,
                height: 20,
                width: 18,
                font:16,
                type: "text",
                text: "t",
                valid: true,
              },
              {
                top: 290,
                left: 340,
                height: 20,
                width: 18,
                font:16,
                type: "text",
                textTopOverride:2,
                text: "t",
                valid: true,
              },
              {
                top: 290,
                left: 400,
                height: 20,
                font:16,
                width: 18,
                type: "text",
                text: "t",
                textTopOverride:2,
                valid: true,
              },
              {
                top: 65,
                left: 130,
                width: 15,
                height: 15,
                area: {
                  top: 60,
                  left: 50,
                  width: 60,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 85,
                left: 127,
                width: 12,
                height: 12,
                area: {
                  top: 80,
                  left: 75,
                  width: 60,
                  height: 30,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 128,
                left: 160,
                width: 12,
                height: 12,
                area: {
                  top: 120,
                  left: 100,
                  width: 50,
                  height: 30,
                },

                type: "multiple",
                valid: true,     //2 mcq..a zebra
              },
              {
                top: 150,
                left: 160,
                width: 15,
                height: 15,
                area: {
                  top: 130,
                  left: 100,
                  width: 50,
                  height: 40,
                },

                type: "multiple",
                valid: false,     //2 mcq..a zebra
              },
              {
                top: 202,
                left: 128,
                width: 12,
                height: 12,
                area: {
                  top: 200,
                  left: 80,
                  width: 30,
                  height: 60,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 226,
                left: 128,
                width: 15,
                height: 15,
                area: {
                  top: 217,
                  left: 80,
                  width: 30,
                  height: 60,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 150,
                left: 160,
                width: 15,
                height: 15,
                area: {
                  top: 140,
                  left: 120,
                  width: 50,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },

              {
                top: 268,
                left: 167,
                width: 12,
                height: 12,
                area: {
                  top: 255,
                  left: 130,
                  width: 50,
                  height: 30,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 290,
                left: 155,
                width: 15,
                height: 15,
                area: {
                  top: 290,
                  left: 130,
                  width: 50,
                  height: 30,
                },

                type: "multiple",
                valid: false,
              },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 8,
      width: 450,
      height: 180,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 93,
                left: 145,
                width: 15,
                height: 15,
                area: {
                  top: 65,
                  left: 145,
                  width: 40,
                  height: 50,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 93,
                left: 177,
                width: 15,
                height: 15,
                area: {
                  top: 65,
                  left: 170,
                  width: 50,
                  height: 60,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 150,
                left: 150,
                width: 15,
                height: 15,
                area: {
                  top: 80,
                  left: 145,
                  width: 40,
                  height: 50,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 150,
                left: 177,
                width: 15,
                height: 15,
                area: {
                  top: 80,
                  left: 165,
                  width: 40,
                  height: 50,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 92,
                left: 350,
                width: 15,
                height: 15,
                area: {
                  top: 65,
                  left: 330,
                  width: 50,
                  height: 60,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 93,
                left: 380,
                width: 15,
                height: 15,
                area: {
                  top: 65,
                  left: 350,
                  width: 50,
                  height: 60,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 150,
                left: 350,
                width: 15,
                height: 15,
                area: {
                  top: 120,
                  left: 350,
                  width: 50,
                  height: 60,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 150,
                left: 380,
                width: 15,
                height: 15,
                area: {
                  top: 120,
                  left: 360,
                  width: 50,
                  height: 60,
                },

                type: "multiple",
                valid: false,
              },
            ],
          },
          ],

      },
    },
  ],
};
