var apb_u_7_27 = {
  id: 27,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 375,
      zoom: {
        answers: [],
      },
    },
    {
      top: 390,
      left: 8,
      width: 450,
      height: 210,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 65,
                left: 103,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "b",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 58,
                left: 149,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "C",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 65,
                left: 205,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "d",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 58,
                left: 246,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "E",
                valid: true,
                textTopOverride: -2,
              },

              {
                top: 65,
                left: 303,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "f",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 58,
                left: 341,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "G",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 96,
                left: 56,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "h",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 96,
                left: 103,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "i",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 94,
                left: 152,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "j",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 92,
                left: 192,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "K",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 96,
                left: 250,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "l",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 96,
                left: 299,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "m",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 96,
                left: 347,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "n",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 128,
                left: 100,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "O",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 128,
                left: 149,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "P",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 128,
                left: 194,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "Q",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 128,
                left: 253,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "R",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 128,
                left: 296,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "S",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 128,
                left: 346,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "T",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 165,
                left: 107,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "u",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 165,
                left: 156,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "v",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 163,
                left: 196,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "W",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 165,
                left: 257,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "x",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 163,
                left: 295,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "Y",
                valid: true,
                textTopOverride: -2,
              },
              {
                top: 163,
                left: 343,
                width: 20,
                height: 20,
                font: 20,
                type: "text",
                text: "Z",
                valid: true,
                textTopOverride: -2,
              },
            ],
          },
        ],
      },
    },
  ],
};
