var apb_u_7_29 = {
  id: 29,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 180,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 93,
                left: 145,
                width: 15,
                height: 15,
                area: {
                  top: 91,
                  left: 145,
                  width: 20,
                  height: 17,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 93,
                left: 177,
                width: 15,
                height: 15,
                area: {
                  top: 91,
                  left: 175,
                  width: 20,
                  height: 17,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 150,
                left: 150,
                width: 15,
                height: 15,
                area: {
                  top: 148,
                  left: 147,
                  width: 20,
                  height: 17,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 150,
                left: 177,
                width: 15,
                height: 15,
                area: {
                  top: 147,
                  left: 175,
                  width: 20,
                  height: 17,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 92,
                left: 350,
                width: 15,
                height: 15,
                area: {
                  top: 90,
                  left: 348,
                  width: 20,
                  height: 17,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 93,
                left: 380,
                width: 15,
                height: 15,
                area: {
                  top: 91,
                  left: 378,
                  width: 20,
                  height: 17,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 150,
                left: 350,
                width: 15,
                height: 15,
                area: {
                  top: 148,
                  left: 347,
                  width: 20,
                  height: 20,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 150,
                left: 380,
                width: 15,
                height: 15,
                area: {
                  top: 148,
                  left: 377,
                  width: 20,
                  height: 20,
                },

                type: "multiple",
                valid: false,
              },
            ],
          },
        ],
      },
    },
    {
      top: 195,
      left: 8,
      width: 450,
      height: 400,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 95,
                left: 293,
                height: 18,
                width: 18,
                font: 16,
                type: "text",
                textTopOverride: 2,
                text: "l",
                valid: true,
              },
              {
                top: 95,
                left: 365,
                height: 18,
                width: 18,
                font: 16,
                type: "text",
                textTopOverride: 2,
                text: "l",
                valid: true,
              },
              {
                top: 95,
                left: 405,
                height: 18,
                width: 18,
                font: 16,
                textTopOverride: 2,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 122,
                left: 256,
                height: 20,
                textTopOverride: 2,
                width: 18,
                font: 16,
                type: "text",
                text: "p",
                valid: true,
              },
              {
                top: 122,
                left: 357,
                height: 20,
                width: 18,
                textTopOverride: 2,
                font: 16,
                type: "text",
                text: "p",
                valid: true,
              },
              {
                top: 122,
                left: 408,
                height: 20,
                textTopOverride: 2,
                width: 18,
                font: 16,
                type: "text",
                text: "p",
                valid: true,
              },
              {
                top: 157,
                left: 256,
                height: 20,
                textTopOverride: 2,
                font: 16,
                width: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 157,
                left: 338,
                height: 20,
                textTopOverride: 2,
                font: 16,
                width: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 157,
                left: 408,
                height: 20,
                textTopOverride: 2,
                font: 16,
                width: 18,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 195,
                left: 278,
                textTopOverride: 2,
                font: 16,
                height: 20,
                width: 18,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 195,
                left: 360,
                height: 20,
                textTopOverride: 2,
                font: 16,
                width: 18,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 195,
                left: 408,
                height: 20,
                font: 16,
                width: 18,
                textTopOverride: 2,
                type: "text",
                text: "r",
                valid: true,
              },
              {
                top: 229,
                left: 267,
                font: 16,
                height: 20,
                width: 18,
                textTopOverride: -2,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 229,
                left: 338,
                height: 20,
                font: 16,
                width: 18,
                textTopOverride: -2,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 229,
                left: 408,
                textTopOverride: 2,
                height: 20,
                font: 16,
                width: 18,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 259,
                textTopOverride: 2,
                left: 278,
                height: 20,
                width: 18,
                font: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 259,
                left: 348,
                textTopOverride: 2,
                height: 20,
                width: 18,
                font: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 259,
                left: 408,
                textTopOverride: 2,
                height: 20,
                width: 18,
                font: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 290,
                left: 278,
                textTopOverride: 2,
                height: 20,
                width: 18,
                font: 16,
                type: "text",
                text: "t",
                valid: true,
              },
              {
                top: 290,
                left: 340,
                height: 20,
                width: 18,
                font: 16,
                type: "text",
                textTopOverride: 2,
                text: "t",
                valid: true,
              },
              {
                top: 290,
                left: 408,
                height: 20,
                font: 16,
                width: 18,
                type: "text",
                text: "t",
                textTopOverride: 2,
                valid: true,
              },
              {
                top: 65,
                left: 130,
                width: 15,
                height: 15,
                area: {
                  top: 63,
                  left: 126,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 87,
                left: 129,
                width: 12,
                height: 12,
                area: {
                  top: 84,
                  left: 126,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 130,
                left: 161,
                width: 12,
                height: 12,
                area: {
                  top: 128,
                  left: 160,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: true, //2 mcq..a zebra
              },
              {
                top: 150,
                left: 160,
                width: 15,
                height: 15,
                area: {
                  top: 150,
                  left: 160,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: false, //2 mcq..a zebra
              },
              {
                top: 204,
                left: 129,
                width: 12,
                height: 12,
                area: {
                  top: 202,
                  left: 128,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 226,
                left: 128,
                width: 15,
                height: 15,
                area: {
                  top: 226,
                  left: 128,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 150,
                left: 160,
                width: 15,
                height: 15,
                area: {
                  top: 150,
                  left: 160,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: false,
              },

              {
                top: 270,
                left: 167,
                width: 12,
                height: 12,
                area: {
                  top: 268,
                  left: 167,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 290,
                left: 155,
                width: 15,
                height: 15,
                area: {
                  top: 290,
                  left: 155,
                  width: 17,
                  height: 17,
                },

                type: "multiple",
                valid: false,
              },
            ],
          },
        ],
      },
    },
  ],
};
