var work_u_3_39= {
    id: 39,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 330,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 145,
                  left: 155,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "eating",
                  valid: true,
                },
                {
                  top: 180,
                  left: 180,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "drinking",
                  valid: true,
                },
                {
                  top: 215,
                  left: 145,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Playing",
                  valid: true,
                },
                {
                  top: 270,
                  left: 255,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 290,
                  left: 245,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "am",
                  valid: true,
                },
                {
                  top: 310,
                  left: 275,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "are",
                  valid: true,
                },
                {
                  top: 290,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "is",
                  valid: true,
                },
                {
                  top: 310,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "are",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 360,
          left: 8,
          width: 450,
          height: 350,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 75,
                    left: 190,
                    width: 220,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "They are playing under the table",
                    valid: true,
                  },
                  {
                    top: 118,
                    left: 210,
                    width: 190,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "I am eating a banana",
                    valid: true,
                  },
                  {
                    top: 165,
                    left: 215,
                    width: 190,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "The kittens are drinking water",
                    valid: true,
                  },
                  
                ],
              },
            ],
          },
        },
        
      ],
    };