var work_u_3_58 = {
    id: 58,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 240,
        zoom: {
          answers: [
            {
              paths: [
               
                {
                  top: 171,
                  left: 235,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "ladies",
                  valid: true,
                },
                {
                  top: 190,
                  left: 235,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "cities",
                  valid: true,
                },
                {
                  top: 210,
                  left: 235,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "babies",
                  valid: true,
                },
                {
                  top: 167,
                  left: 55,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "toys",
                  valid: true,
                }, 
                {
                  top: 190,
                  left: 55,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "spiders",
                  valid: true,
                },    
                {
                  top: 210,
                  left: 55,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "horses",
                  valid: true,
                },          
                {
                  top: 189,
                  left: 135,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "glasses",
                  valid: true,
                },   
                {
                  top: 210,
                  left: 135,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "dresses",
                  valid: true,
                },   
                {
                  top: 171,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "childern",
                  valid: true,
                },
                {
                  top: 190,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "mice",
                  valid: true,
                },
                {
                  top: 210,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "theeth",
                  valid: true,
                },   
              ],
            },
          ],
        },
      },
       
        {
          top: 250,
          left: 8,
          width: 450,
          height: 360,
          zoom: {
            answers: [ 
              {
                paths: [
                 
                  {
                    top: 148,
                    left: 250,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "toys",
                    valid: true,
                  },
                  {
                    top: 171,
                    left: 250,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "boys",
                    valid: true,
                  },
                  {
                    top: 170,
                    left: 70,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "spiders",
                    valid: true,
                  },
                  {
                    top: 210,
                    left: 70,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "watches",
                    valid: true,
                  },    
                  {
                    top: 230,
                    left: 70,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "glasses",
                    valid: true,
                  }, 
                  {
                    top: 210,
                    left: 250,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "feet",
                    valid: true,
                  },  
                  {
                    top: 230,
                    left: 250,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "childern",
                    valid: true,
                  }, 
                  {
                    top: 275,
                    left: 70,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "puppies",
                    valid: true,
                  }, 
                  {
                    top: 296,
                    left: 70,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "cities",
                    valid: true,
                  }, 

                ],
              },
             
            ],
          },
        },
        
      ],
    };