var work_u_3_45 = {
    id: 45,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 260,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 100,
                  left: 110,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "bread",
                  valid: true,
                },
                {
                  top: 120,
                  left: 108,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "eat",
                  valid: true,
                },
                {
                  top: 138,
                  left: 109,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "honey",
                  valid: true,
                },
                {
                  top: 178,
                  left: 60,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "smiling",
                  valid: true,
                },
                {
                  top: 200,
                  left: 85,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "milk",
                  valid: true,
                },
                {
                  top: 215,
                  left: 98,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "sleeping",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 270,
          left: 8,
          width: 450,
          height: 310,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 115,
                    left: 170,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Yes, he is",
                    valid: true,
                  },
                  {
                    top: 165,
                    left: 150,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, they αren’t",
                    valid: true,
                  },
                  {
                    top: 230,
                    left: 145,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Yes they αre",
                    valid: true,
                  },
                  {
                    top: 273,
                    left: 145,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, i'm not",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };