var work_u_3_59 = {
    id: 59,
    
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 230,
        zoom: {
          answers: [ 
            {
              paths: [
                {
                  top: 125,
                  left: 235,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "A big foot",
                  valid: true,
                }, 
                {
                  top: 159,
                  left: 235,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "A lazy child",
                  valid: true,
                },
                {
                  top: 195,
                  left: 235,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "An old man",
                  valid: true,
                },
                
              ],
            },
           
          ],
        },
      },
       
        {
          top: 250,
          left: 8,
          width: 450,
          height: 370,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 45,
                    left: 160,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Six new toys",
                    valid: true,
                  }, 
                 
                  {
                    top: 70,
                    left: 167,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"Four old women",
                    valid: true,
                  }, 
                  {
                    top: 90,
                    left: 164,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"Three big cities",
                    valid: true,
                  }, 
                  {
                    top: 110,
                    left: 155,
                    width: 140,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"Five yellow brushes",
                    valid: true,
                  }, 
                  {
                    top: 132,
                    left: 156,
                    width: 140,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"Four new watches",
                    valid: true,
                  }, 
                  {
                    top: 210,
                    left: 215,
                    width: 140,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"The baby is playing",
                    valid: true,
                  }, 
                  {
                    top: 230,
                    left: 212,
                    width: 220,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"That women is having breakfast",
                    valid: true,
                  }, 
                  {
                    top: 253,
                    left: 215,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"My tooth is white ",
                    valid: true,
                  }, 
                  {
                    top: 275,
                    left: 215,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"This is a balck spider ",
                    valid: true,
                  }, 
                  {
                    top: 296,
                    left: 210,
                    width: 230,
                    height: 16,
                    font: 12,
                    type: "text",
                    text:"The lαdy hαs got αn empty glαss ",
                    valid: true,
                  }, 
                ],
              },
            ],
          },
        },
        
      ],
    };