var work_u_3_46 = {
    id: 46,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 460,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 140,
                  left: 280,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "a bird can",
                  valid: true,
                },
                {
                  top: 159,
                  left: 270,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "sing",
                  valid: true,
                },
                {
                  top: 235,
                  left: 250,
                  width: 170,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "The/Α cαt cαn sleep in the",
                  valid: true,
                },
                {
                  top: 253,
                  left: 260,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "basket",
                  valid: true,
                },
                {
                  top: 235,
                  left: 50,
                  width: 170,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "parrots can",
                  valid: true,
                },
                {
                  top: 253,
                  left: 70,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "talk",
                  valid: true,
                },
                {
                  top: 320,
                  left: 50,
                  width: 170,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "The girl can brush",
                  valid: true,
                },
                {
                  top: 340,
                  left: 70,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "their teeth",
                  valid: true,
                },
                {
                  top: 320,
                  left: 250,
                  width: 170,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "The/Αn elephαnt cαn",
                  valid: true,
                },
                {
                  top: 340,
                  left: 260,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "eat bananas",
                  valid: true,
                },
                {
                  top: 420,
                  left: 50,
                  width: 170,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Tom can read English",
                  valid: true,
                },
                {
                  top: 440,
                  left: 70,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "books",
                  valid: true,
                },
                {
                  top: 420,
                  left: 250,
                  width: 170,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "The penguin can play",
                  valid: true,
                },
                {
                  top: 440,
                  left: 270,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "music",
                  valid: true,
                },
              ],
            },
           
          ],
        },
      },
       
        {
          top: 470,
          left: 8,
          width: 450,
          height: 150,
          zoom: {
            answers: [
             
            ],
          },
        },
        
      ],
    };