var work_u_3_44= {
    id: 44,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 310,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 90,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "waiting",
                  valid: true,
                },
                {
                  top: 113,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "cooking",
                  valid: true,
                },
                {
                  top: 136,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "writing",
                  valid: true,
                },
                {
                  top: 115,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "making",
                  valid: true,
                },
                {
                  top: 136,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "doing",
                  valid: true,
                },
                {
                  top: 155,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "eating",
                  valid: true,
                },
                {
                  top: 155,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "closing",
                  valid: true,
                },
                {
                  top: 230,
                  left: 230,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "He is helping tom",
                  valid: true,
                },
                {
                  top: 255,
                  left: 230,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "I am watching TV",
                  valid: true,
                },
                {
                  top: 275,
                  left: 230,
                  width: 150,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "We are driving our car",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 320,
          left: 8,
          width: 450,
          height: 330,
          zoom: {
            answers: [
              {
                paths: [
                
                  {
                    top: 95,
                    left: 250,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "They're making",
                    valid: true,
                  },
                  {
                    top: 110,
                    left: 260,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "breakfast",
                    valid: true,
                  },
                  {
                    top: 209,
                    left: 245,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "The girls cooking",
                    valid: true,
                  },
                  {
                    top: 226,
                    left: 250,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "in the kitchean",
                    valid: true,
                  },
                  {
                    top: 209,
                    left: 70,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "The teαcher’s writing",
                    valid: true,
                  },
                  {
                    top: 226,
                    left: 70,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "on the whiteboard",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };