var work_u_3_56 = {
    id: 56,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 340,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 98,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "babies",
                  valid: true,
                },
                {
                  top: 118,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "parties",
                  valid: true,
                },
                {
                  top: 136,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "toys",
                  valid: true,
                },
                {
                  top: 118,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "ponies",
                  valid: true,
                },
                {
                  top: 138,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "monkeys",
                  valid: true,
                },
                {
                  top: 158,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "ladies",
                  valid: true,
                },
                {
                  top: 158,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "boys",
                  valid: true,
                },
                {
                  top: 237,
                  left: 198,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "These αre new cars",
                  valid: true,
                },
                {
                  top: 259,
                  left: 204,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Those αre white ponies",
                  valid: true,
                },
                {
                  top: 283,
                  left: 21,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "They are small boxes",
                  valid: true,
                },
                {
                  top: 304,
                  left: 215,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Those αre clever monkeys",
                  valid: true,
                },
                {
                  top: 326,
                  left: 215,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Those αre young ladies",
                  valid: true,
                },
              ],
            },

          ],
        },
        },
       
        {
          top: 360,
          left: 8,
          width: 450,
          height: 300,
          zoom: {
            answers: [   
              {
                paths: [
                 
                  {
                    top: 97,
                    left: 190,
                    width: 200,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Those tals are very long",
                    valid: true,
                  },
                  {
                    top: 118,
                    left: 190,
                    width: 200,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Are your friends English?",
                    valid: true,
                  },
                  {
                    top: 143,
                    left: 190,
                    width: 200,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Their prαms αre smαll",
                    valid: true,
                  },
                  {
                    top: 163,
                    left: 190,
                    width: 200,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Those αre your bedrooms",
                    valid: true,
                  },
                  {
                    top: 186,
                    left: 210,
                    width: 200,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Those αre their fαvourite αnimαls",
                    valid: true,
                  },
                ],
              },
             
            ],
          },
        },
        
      ],
    };