var work_u_3_54 = {
    id: 54,
    
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 330,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 104,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "brushes",
                  valid: true,
                },
                {
                  top: 123,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "prams",
                  valid: true,
                },
                {
                  top: 142,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "nurses",
                  valid: true,
                },
                {
                  top: 122,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "watches",
                  valid: true,
                },
                {
                  top: 143,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "boxes",
                  valid: true,
                },
                {
                  top: 162,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "buses",
                  valid: true,
                },
                {
                  top: 162,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "ears",
                  valid: true,
                },
                {
                  top: 234,
                  left: 190,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "These αre four short tαils",
                  valid: true,
                },
                {
                  top: 257,
                  left: 190,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Those αre three English houses",
                  valid: true,
                },
                {
                  top: 279,
                  left: 190,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "These αre eight fαst horses",
                  valid: true,
                },
                {
                  top: 300,
                  left: 190,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Those αre ten white dresses",
                  valid: true,
                },
              ],
            },
           
          ],
        },
      },
       
        {
          top: 340,
          left: 8,
          width: 450,
          height: 260,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 89,
                    left: 200,
                    width: 50,
                    height:16,
                    font:12,
                    type: "text",
                    text: " red",
                    valid: true
                  },
                  {
                    top: 105,
                    left: 196,
                    font:12,
                    width: 50,
                    height:16,
                    type: "text",
                    text: "rose",
                    valid: true
                  },
                  {
                    top: 89,
                    left: 305,
                    width: 90,
                    height:16,
                    font:12,
                    type: "text",
                    text: "Two clever",
                    valid: true
                  },
                  {
                    top: 105,
                    left: 315,
                    font:12,
                    width: 50,
                    height:16,
                    type: "text",
                    text: "boys",
                    valid: true
                  },
                  {
                    top: 190,
                    left: 185,
                    width:90,
                    height:16,
                    font:12,
                    type: "text",
                    text: "Two white",
                    valid: true
                  },
                  {
                    top: 208,
                    left: 196,
                    font:12,
                    width: 50,
                    height:16,
                    type: "text",
                    text: "horses",
                    valid: true
                  },
                  {
                    top: 190,
                    left: 305,
                    width:90,
                    height:16,
                    font:12,
                    type: "text",
                    text: "Two red",
                    valid: true
                  },
                  {
                    top: 208,
                    left: 315,
                    font:12,
                    width: 50,
                    height:16,
                    type: "text",
                    text: "buses",
                    valid: true
                  },
                  {
                    top: 190,
                    left: 60,
                    width:90,
                    height:16,
                    font:12,
                    type: "text",
                    text: "Three long",
                    valid: true
                  },
                  {
                    top: 206,
                    left: 70,
                    font:12,
                    width: 60,
                    height:16,
                    type: "text",
                    text: "dresses",
                    valid: true
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };