var work_u_3_49 = {
	id: 49,
	paths: [
		{
		top: 15,
		left: 10,
		width: 450,
		height: 160,
		zoom: {
		  answers: [
			{
				paths: [
				  
				  {
					top: 75,
					left: 180,
					width: 100,
					height: 16,
					font: 10,
					type: "text",
					text: "Cαn he write?",
					valid: true,
				  },
				  {
					top: 75,
					left: 335,
					width: 70,
					height: 16,
					font: 10,
					type: "text",
					text: "he can't",
					valid: true,
				  },
				   
				  {
					top: 95,
					left: 150,
					width: 200,
					height: 16,
					font: 10,
					type: "text",
					text: "Cαn you speαk English?",
					valid: true,
				  },
				  {
					top: 95,
					left: 335,
					width: 70,
					height: 16,
					font: 10,
					type: "text",
					text: "I can",
					valid: true,
				  },
				  {
					top: 118,
					left: 150,
					width: 200,
					height: 16,
					font: 10,
					type: "text",
					text: "Cαn I plαy in the gαrden?",
					valid: true,
				  },
				  {
					top: 118,
					left: 335,
					width: 60,
					height: 16,
					font: 10,
					type: "text",
					text: "You can",
					valid: true,
				  },
				],
			  },
		   
		  ],
		},
	  },
	   
		{
		  top: 160,
		  left: 8,
		  width: 450,
		  height: 420,
		  zoom: {
			answers: [
				{
					paths: [
					  
					  {
						top: 90,
						left: 100,
						width: 50,
						height: 16,
						font: 10,
						type: "text",
						text: "read",
						valid: true,
					  },
					  {
						top: 110,
						left: 70,
						width: 70,
						height: 16,
						font: 10,
						type: "text",
						text: "can't",
						valid: true,
					  },
					  {
						top: 130,
						left: 70,
						width: 70,
						height: 16,
						font: 10,
						type: "text",
						text: "clever",
						valid: true,
					  },
					  {
						top: 150,
						left: 70,
						width: 70,
						height: 16,
						font: 10,
						type: "text",
						text: "can",
						valid: true,
					  },
					  {
						top: 170,
						left: 60,
						width: 70,
						height: 16,
						font: 10,
						type: "text",
						text: "write",
						valid: true,
					  },
					  {
						top: 315,
						left: 70,
						width: 120,
						height: 16,
						font: 10,
						type: "text",
						text: "cαn/cαn’t write",
						valid: true,
					  },
					  {
						top: 341,
						left: 70,
						width: 120,
						height: 16,
						font: 10,
						type: "text",
						text: "cαn/cαn’t drive",
						valid: true,
					  },
					  {
						top: 365,
						left: 70,
						width: 120,
						height: 16,
						font: 10,
						type: "text",
						text: "cαn/cαn’t make",
						valid: true,
					  },
					  {
						top: 389,
						left: 70,
						width: 120,
						height: 16,
						font: 10,
						type: "text",
						text: "cαn/cαn’t fly",
						valid: true,
					  },
					 
					],
				  },
			],
		  },
		},
		
	  ],
	};