var apb_u_2_8 = {
  id: 8,
  paths: [
    {
      top: 10,
      left: 9,
      width: 450,
      height: 340,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 46,
                left: 40,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 46,
                left: 53,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
                font: 16,
              },
              {
                top: 46,
                left: 70,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
                font: 16,
              },
              {
                top: 81,
                left: 79,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
                font: 16,
              },
              {
                top: 114,
                left: 79,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 114,
                left: 95,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 143,
                left: 133,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 143,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
                font: 16,
              },
              {
                top: 143,
                left: 180,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 143,
                left: 203,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 143,
                left: 230,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 175,
                left: 160,
                width: 14,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 175,
                left: 199,
                width: 13,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 175,
                left: 284,
                width: 12,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
                font: 16,
              },
              {
                top: 198,
                left: 25,
                width: 13,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
                font: 16,
              },
              {
                top: 198,
                left: 40,
                width: 13,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 258,
                left: 253,
                width: 13,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 258,
                left: 272,
                width: 13,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
                font: 16,
              },
              {
                top: 300,
                left: 28,
                width: 13,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 300,
                left: 65,
                width: 13,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 327,
                left: 214,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 327,
                left: 250,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 327,
                left: 295,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
            ],
          },
        ],
      },
    },
    {
      top: 350,
      left: 8,
      width: 440,
      height: 240,
      zoom: {
        answers: [
          {
            paths: [
              {
                type: "underline",
                top: 138,
                left: 242,
                width: 119,
                rotate: 59,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 92,
                left: 262,
                width: 8,
                area: {
                  top: 95,
                  left: 258,
                  width: 8,
                  height: 8,
                },
                underline: 1,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 157,
                left: 254,
                width: 139,
                rotate: 37,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 123,
                left: 262,
                width: 8,
                area: {
                  top: 126,
                  left: 258,
                  width: 8,
                  height: 8,
                },
                underline: 2,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 155,
                left: 270,
                width: 90,
                rotate: 10,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 154,
                left: 262,
                width: 8,
                area: {
                  top: 157,
                  left: 258,
                  width: 8,
                  height: 8,
                },
                underline: 3,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 131,
                left: 245,
                width: 160,
                rotate: -37,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 185,
                left: 262,
                width: 8,
                area: {
                  top: 188,
                  left: 258,
                  width: 8,
                  height: 8,
                },
                underline: 4,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 140,
                left: 222,
                width: 162,
                rotate: -58,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 216,
                left: 262,
                width: 8,
                area: {
                  top: 219,
                  left: 258,
                  width: 8,
                  height: 8,
                },
                underline: 5,
                type: "checkmark",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
