var apb_u_2_8 = {
  id: 8,
  paths: [
    {
      top: 350,
      left: 8,
      width: 440,
      height: 240,
      zoom: {
        answers: [
          {
            paths: [
              {
                type: "underline",
                top: 138,
                left: 242,
                width: 119,
                rotate: 59,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 95,
                left: 258,
                width: 8,
                area: {
                    top: 95,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 1,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 157,
                left: 254,
                width: 139,
                rotate: 37,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 126,
                left: 258,
                width: 8,
                area: {
                    top: 126,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 2,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 155,
                left: 270,
                width: 90,
                rotate: 10,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 157,
                left: 258,
                width: 8,
                area: {
                    top: 157,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 3,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 131,
                left: 245,
                width: 160,
                rotate: -37,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 188,
                left: 258,
                width: 8,
                area: {
                    top: 188,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 4,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 140,
                left: 222,
                width: 162,
                rotate: -58,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 219,
                left: 258,
                width: 8,
                area: {
                    top: 219,
                    left: 258,
                    width: 8,
                    height: 8
                }, 
                underline: 5,
                type: "checkmark",
                valid: true
            },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 9,
      width: 450,
      height: 340,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 43,
                left: 40,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 43,
                left: 53,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 43,
                left: 70,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 76,
                left: 79,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 110,
                left: 79,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 110,
                left: 95,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 139,
                left: 133,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 139,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 139,
                left: 180,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 139,
                left: 203,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 139,
                left: 230,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 173,
                left: 160,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 173,
                left: 195,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 173,
                left: 280,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 195,
                left: 25,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 195,
                left: 40,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 255,
                left: 250,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 255,
                left: 270,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 300,
                left: 25,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 300,
                left: 65,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 324,
                left: 214,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 323,
                left: 250,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 324,
                left: 295,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
