var work_u_4_78= {
    id: 78,
    
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 370,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 93,
                  left: 275,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "lives",
                  valid: true,
                },
                {
                  top: 115,
                  left: 295,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "makes",
                  valid: true,
                },
                {
                  top: 134,
                  left: 290,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "getsup",
                  valid: true,
                },
                {
                  top: 114,
                  left: 90,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "reads",
                  valid: true,
                },
                {
                  top: 134,
                  left: 85,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "works",
                  valid: true,
                },
               
                {
                  top: 210,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "read",
                  valid: true,
                },
                {
                  top: 230,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "reads",
                  valid: true,
                },
                {
                  top: 250,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "reads",
                  valid: true,
                },
                {
                  top: 274,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "reads",
                  valid: true,
                },
                {
                  top: 293,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "read",
                  valid: true,
                },
                {
                  top: 315,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "read",
                  valid: true,
                },
                {
                  top: 335,
                  left: 70,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "read",
                  valid: true,
                },
               
              ],
            },
          ],
        },
      },
       
        {
          top: 380,
          left: 8,
          width: 450,
          height: 260,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 88,
                    left: 275,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "in Austria.",
                    valid: true,
                  },
                  {
                    top: 110,
                    left: 235,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "She works in a hospital.",
                    valid: true,
                  },
                  {
                    top: 130,
                    left: 235,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "She likes sports.",
                    valid: true,
                  },
                  {
                    top: 150,
                    left: 230,
                    width: 180,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "She plαys tennis every dαy.",
                    valid: true,
                  },

               
                 
                ],
              },
            ],
          },
        },
        
      ],
    };