var work_u_4_92 = {
    id: 92,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 235,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 120,
                  left: 270,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "July",
                  valid: true,
                },
                {
                  top: 138,
                  left: 100,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "February.",
                  valid: true,
                },
                {
                  top: 138,
                  left: 270,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "August",
                  valid: true,
                },
                {
                  top: 158,
                  left: 100,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "March",
                  valid: true,
                },
                {
                  top: 158,
                  left: 270,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "September",
                  valid: true,
                },
                {
                  top: 178,
                  left: 100,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "April",
                  valid: true,
                },
                {
                  top: 178,
                  left: 270,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "October",
                  valid: true,
                },
                {
                  top: 198,
                  left: 100,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "May",
                  valid: true,
                },
                {
                  top: 198,
                  left: 270,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "November",
                  valid: true,
                },
                {
                  top: 218,
                  left: 100,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "June",
                  valid: true,
                },
                {
                  top: 218,
                  left: 270,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "December",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 250,
          left: 8,
          width: 450,
          height: 360,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 105,
                    left: 70,
                    width: 180,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "eat launch at night. ",
                    valid: true,
                  },
                  {
                    top: 125,
                    left: 40,
                    width: 180,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "She eats launch at noon. ",
                    valid: true,
                  },
                  {
                    top: 160,
                    left: 40,
                    width: 180,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "We don't swim in january. ",
                    valid: true,
                  },
                  {
                    top: 180,
                    left: 40,
                    width: 160,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "We swim in August. ",
                    valid: true,
                  },
                  {
                    top: 220,
                    left: 40,
                    width: 220,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "I don't watch TV in the morning. ",
                    valid: true,
                  },
                  {
                    top: 240,
                    left: 40,
                    width: 220,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "I watch TV in the afternoon. ",
                    valid: true,
                  },
                  {
                    top: 276,
                    left: 40,
                    width: 240,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Brendα doesn’t plαy tennis on Mondαy. ",
                    valid: true,
                  },
                  {
                    top: 296,
                    left: 40,
                    width: 220,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Brendα plαys tennis on Saturday. ",
                    valid: true,
                  },
                  
                ],
              },
            ],
          },
        },
        
      ],
    };