var work_u_4_86= {
    id: 86,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 220,
        zoom: {
          answers: [
            {
              paths: [
               
             
                {
                  top: 155,
                  left: 85,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "swims",
                  valid: true,
                },
                {
                  top: 155,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "lake",
                  valid: true,
                },
                {
                  top: 177,
                  left: 88,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "rides",
                  valid: true,
                },
                {
                  top: 177,
                  left: 220,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "bikes",
                  valid: true,
                },
                {
                  top: 197,
                  left: 110,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "eats",
                  valid: true,
                },
                {
                  top: 197,
                  left: 210,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "fish",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 230,
          left: 8,
          width: 450,
          height: 360,
          zoom: {
            answers: [
              {
                paths: [
                 
               
                
                  {
                    top: 207,
                    left: 218,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "he does",
                    valid: true,
                  },
                  {
                    top: 207,
                    left: 335,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "he doesn't",
                    valid: true,
                  },
                  {
                    top: 230,
                    left: 218,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "yes,They do",
                    valid: true,
                  },
                  {
                    top: 230,
                    left: 300,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, They don't",
                    valid: true,
                  },
                  {
                    top: 255,
                    left: 218,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "yes,I do",
                    valid: true,
                  },
                  {
                    top: 255,
                    left: 300,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, I don't",
                    valid: true,
                  },
                  {
                    top: 275,
                    left: 218,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "yes,I do",
                    valid: true,
                  },
                  {
                    top: 275,
                    left: 300,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, I don't",
                    valid: true,
                  },
                  {
                    top: 315,
                    left: 218,
                    width: 70,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "yes,we do",
                    valid: true,
                  },
                  {
                    top: 315,
                    left: 300,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No, we don't",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };