var work_u_4_67= {
    id: 67,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 220,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 130,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "he",
                  valid: true,
                },
                {
                  top: 130,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "him",
                  valid: true,
                },
                {
                  top: 150,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "they",
                  valid: true,
                },
                {
                  top: 150,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "them",
                  valid: true,
                },
                {
                  top: 170,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "we",
                  valid: true,
                },
                {
                  top: 170,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "us",
                  valid: true,
                },
                {
                  top: 190,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "you",
                  valid: true,
                },
                {
                  top: 190,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "you",
                  valid: true,
                },
                {
                  top: 210,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "it",
                  valid: true,
                },
                {
                  top: 210,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "it",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 230,
          left: 8,
          width: 450,
          height: 390,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 85,
                    left: 30,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No she can't see him",
                    valid: true,
                  },
                  {
                    top: 125,
                    left: 30,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "No she can't see her",
                    valid: true,
                  },
                  {
                    top: 160,
                    left: 40,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "I can can see him",
                    valid: true,
                  },
                  {
                    top: 238,
                    left: 275,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "them",
                    valid: true,
                  },
                  {
                    top: 277,
                    left: 55,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "he",
                    valid: true,
                  },
                  {
                    top: 277,
                    left:130,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "them",
                    valid: true,
                  },
                  {
                    top: 277,
                    left: 240,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "I",
                    valid: true,
                  },
                  {
                    top: 277,
                    left:320,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "him",
                    valid: true,
                  },
                  {
                    top: 316,
                    left: 55,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "I",
                    valid: true,
                  },
                  {
                    top: 316,
                    left:130,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "it",
                    valid: true,
                  },
                  {
                    top: 316,
                    left: 300,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "them",
                    valid: true,
                  },
                  
                ],
              },
            ],
          },
        },
        
      ],
    };