var work_u_4_93= {
    id: 93,
    
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 400,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 70,
                  left: 350,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in",
                  valid: true,
                },
                {
                  top: 90,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in",
                  valid: true,
                },
                {
                  top: 90,
                  left: 350,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "at",
                  valid: true,
                },
                {
                  top: 110,
                  left: 250,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in",
                  valid: true,
                },
                {
                  top: 178,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "at",
                  valid: true,
                },
               
                {
                  top: 195,
                  left: 200,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in",
                  valid: true,
                },
                {
                  top: 195,
                  left: 340,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in",
                  valid: true,
                },
               
                {
                  top: 215,
                  left: 330,
                  width: 70,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in front of",
                  valid: true,
                },
                {
                  top: 250,
                  left: 250,
                  width: 70,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "behind",
                  valid: true,
                },
                {
                  top: 300,
                  left: 300,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in",
                  valid: true,
                },
                {
                  top: 320,
                  left: 220,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "to",
                  valid: true,
                },
                {
                  top: 320,
                  left: 280,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "at",
                  valid: true,
                },
                {
                  top: 340,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "on",
                  valid: true,
                },
                {
                  top: 340,
                  left: 330,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "in",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 420,
          left: 8,
          width: 450,
          height: 260,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 40,
                    left: 150,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "after",
                    valid: true,
                  },
                  {
                    top: 65,
                    left: 80,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "in",
                    valid: true,
                  },
                  {
                    top: 65,
                    left: 180,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "with",
                    valid: true,
                  },
                  {
                    top: 85,
                    left: 120,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "at",
                    valid: true,
                  },
                  {
                    top: 105,
                    left: 45,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "In",
                    valid: true,
                  },
                  {
                    top: 105,
                    left: 180,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "to",
                    valid: true,
                  },
                  {
                    top: 105,
                    left: 270,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "after",
                    valid: true,
                  },
                  {
                    top: 125,
                    left: 90,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "with",
                    valid: true,
                  },
                  {
                    top: 125,
                    left: 200,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "to",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };