var work_u_4_72= {
    id: 72,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 570,
        zoom: {
          answers: [
            {
              paths: [
               
                {
                  top: 218,
                  left: 60,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "open your ",
                  valid: true,
                },
                {
                  top: 235,
                  left: 80,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "mouth",
                  valid: true,
                },
                {
                  top: 218,
                  left: 190,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Come here, ",
                  valid: true,
                },
                {
                  top: 235,
                  left: 195,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "please!",
                  valid: true,
                },
                {
                  top: 218,
                  left: 320,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Come in, ",
                  valid: true,
                },
                {
                  top: 235,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "please!",
                  valid: true,
                },
                {
                  top: 340,
                  left: 60,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Be careful!" ,
                  valid: true,
                },
                {
                  top: 340,
                  left: 190,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Stand up!" ,
                  valid: true,
                },
                {
                  top: 340,
                  left: 320,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Please" ,
                  valid: true,
                },
                {
                  top: 360,
                  left: 320,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "sit down!" ,
                  valid: true,
                },
                {
                  top: 467,
                  left: 60,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Answer the!" ,
                  valid: true,
                },
                {
                  top: 485,
                  left: 60,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "phone please!" ,
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 0,
          left: 8,
          width: 450,
          height: 0,
          zoom: {
            answers: [
             
            ],
          },
        },
        
      ],
    };