var work_u_4_70 = {
    id: 70,
    
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 410,
        zoom: {
          answers: [
            {
              paths: [
               
                {
                  top: 175,
                  left: 220,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "are the ",
                  valid: true,
                },
                {
                  top: 197,
                  left: 180,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "girl's dresses.",
                  valid: true,
                },
                {
                  top: 175,
                  left: 320,
                  width: 60,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "These are  ",
                  valid: true,
                },
                {
                  top: 197,
                  left: 290,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Ted's glasses.",
                  valid: true,
                },
                {
                  top: 175,
                  left: 320,
                  width: 60,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "These are  ",
                  valid: true,
                },
                {
                  top: 197,
                  left: 320,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Ted's glasses.",
                  valid: true,
                }, 
                {
                  top: 325,
                  left: 70,
                  width: 60,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "This is my  ",
                  valid: true,
                },
                {
                  top: 345,
                  left: 30,
                  width: 130,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "sister’s bedroom.",
                  valid: true,
                }, 
                {
                  top: 325,
                  left: 180,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "These are the  ",
                  valid: true,
                },
                {
                  top: 345,
                  left: 170,
                  width: 130,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "boy's books.",
                  valid: true,
                },
                {
                  top: 325,
                  left: 290,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "This is  ",
                  valid: true,
                },
                {
                  top: 345,
                  left: 290,
                  width: 130,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "Simon's desk.",
                  valid: true,
                },  
              ],
            },
          ],
        },
      },
       
        {
          top: 430,
          left: 8,
          width: 450,
          height: 170,
          zoom: {
            answers: [
              {
                paths: [
                 
                  {
                    top: 65,
                    left: 200,
                    width: 120,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "This is our desk. ",
                    valid: true,
                  },
                  {
                    top: 89,
                    left: 200,
                    width: 220,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Susie αnd Bob αre your friends. ",
                    valid: true,
                  },
                  {
                    top: 110,
                    left: 200,
                    width: 220,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Helen hαs got Tony’s glαsses. ",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };