var work_u_4_66 = {
    id: 66,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 240,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 130,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "he",
                  valid: true,
                },
                {
                  top: 130,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "him",
                  valid: true,
                },
                {
                  top: 150,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "they",
                  valid: true,
                },
                {
                  top: 150,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "them",
                  valid: true,
                },
                {
                  top: 170,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "we",
                  valid: true,
                },
                {
                  top: 170,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "us",
                  valid: true,
                },
                {
                  top: 190,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "you",
                  valid: true,
                },
                {
                  top: 190,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "you",
                  valid: true,
                },
                {
                  top: 210,
                  left: 240,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "it",
                  valid: true,
                },
                {
                  top: 210,
                  left: 320,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "it",
                  valid: true,
                },
              ],
            },      
          ],
        },
        },
      
       
        {
          top: 260,
          left: 8,
          width: 450,
          height: 330,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 50,
                    left: 170,
                    width: 100,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "l cαn see her",
                    valid: true,
                  },
                  {
                    top: 70,
                    left: 160,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "She cαn’t heαr you",
                    valid: true,
                  },
                  {
                    top: 90,
                    left: 170,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Is the baby with you?",
                    valid: true,
                  },
                  {
                    top: 110,
                    left: 170,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Can they help him?",
                    valid: true,
                  },
                 
                  {
                    top: 134,
                    left: 170,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Can you do i?",
                    valid: true,
                  },
                  
                  {
                    top: 154,
                    left: 170,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "He can't find her?",
                    valid: true,
                  },
                 
                  {
                    top: 174,
                    left: 170,
                    width: 150,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Dad is watching me",
                    valid: true,
                  },
                  
                ],
              }, 
            ],
          },
        },
        
      ],
    };