var work_u_4_80 = {
    id: 80,
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 300,
        zoom: {
          answers: [
            {
              paths: [
                {
                  top: 98,
                  left: 225,
                  width: 100,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "goes to school.",
                  valid: true,
                },
                {
                  top: 118,
                  left: 225,
                  width: 130,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "comes from Greece.",
                  valid: true,
                },
                {
                  top: 140,
                  left: 225,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "brushes her teeth.",
                  valid: true,
                },
                {
                  top: 162,
                  left: 260,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "wαtches TV.",
                  valid: true,
                },
                {
                  top: 178,
                  left: 244,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "speaks English.",
                  valid: true,
                },
                {
                  top: 198,
                  left: 235,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "makes good bread.",
                  valid: true,
                },
                {
                  top: 220,
                  left: 225,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "washes his face.",
                  valid: true,
                },
                {
                  top: 242,
                  left: 243,
                  width: 120,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "does his homework.",
                  valid: true,
                },
                {
                  top:261,
                  left: 215,
                  width: 200,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "goes to the party everyday.",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 280,
          left: 8,
          width: 450,
          height: 310,
          zoom: {
            answers: [
              {
                paths: [
                  {
                    top: 142,
                    left: 80,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "works",
                    valid: true,
                  },
                  {
                    top: 162,
                    left: 80,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "goes",
                    valid: true,
                  },
                  {
                    top: 184,
                    left: 100,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "gets",
                    valid: true,
                  },
                  {
                    top: 204,
                    left: 145,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "goes",
                    valid: true,
                  },
                  {
                    top: 225,
                    left: 100,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "watches",
                    valid: true,
                  },
                  {
                    top: 245,
                    left: 80,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "reads",
                    valid: true,
                  },
                  {
                    top: 265,
                    left: 105,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "goes",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };