var work_u_4_71 = {
    id: 71,
    
    paths: [
        {
        top: 15,
        left: 10,
        width: 450,
        height: 235,
        zoom: {
          answers: [
            {
              paths: [
               
                {
                  top: 97,
                  left: 110,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "my ",
                  valid: true,
                },
                {
                  top: 117,
                  left: 110,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "coat ",
                  valid: true,
                },
                {
                  top: 139,
                  left: 110,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "his ",
                  valid: true,
                },
                {
                  top: 157,
                  left: 114,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "mum's ",
                  valid: true,
                },
                {
                  top: 178,
                  left: 140,
                  width: 50,
                  height: 16,
                  font: 12,
                  type: "text",
                  text: "shoes ",
                  valid: true,
                },
              ],
            },
          ],
        },
      },
       
        {
          top: 270,
          left: 8,
          width: 450,
          height: 340,
          zoom: {
            answers: [
              {
                paths: [
                 
                  {
                    top: 60,
                    left: 260,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Tony's ",
                    valid: true,
                  },
                  {
                    top: 86,
                    left: 260,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Tony's ",
                    valid: true,
                  },
                  {
                    top: 108,
                    left: 230,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Tony's ",
                    valid: true,
                  },
                  {
                    top: 133,
                    left: 270,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Susie’s ",
                    valid: true,
                  },
                  {
                    top: 157,
                    left: 270,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Susie’s ",
                    valid: true,
                  },
                  {
                    top: 177,
                    left: 230,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Tony’s ",
                    valid: true,
                  },
                  {
                    top: 225,
                    left: 230,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Susie’s ",
                    valid: true,
                  },
                  {
                    top: 225,
                    left: 345,
                    width: 50,
                    height: 16,
                    font: 12,
                    type: "text",
                    text: "Jim’s ",
                    valid: true,
                  },
                ],
              },
            ],
          },
        },
        
      ],
    };