var comp_u_2_25 = {
  id: 25,
  paths: [
    {
      top: 40,
      left: 8,
      width: 450,
      height: 190,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 75,
                left: 250,
                width: 130,
                height: 16,
                font: 12,
                type: "text",
                text: "black boys",
                valid: true,
              },

              {
                top: 115,
                left: 70,
                width: 120,
                height: 16,
                font: 12,
                type: "text",
                text: "green trees",
                valid: true,
              },
              {
                top: 115,
                left: 270,
                width: 120,
                height: 16,
                font: 12,
                type: "text",
                text: "young horses",
                valid: true,
              },

              {
                top: 155,
                left: 70,
                width: 120,
                height: 16,
                font: 12,
                type: "text",
                text: "big houses",
                valid: true,
              },
              {
                top: 155,
                left: 270,
                width: 120,
                height: 16,
                font: 12,
                type: "text",
                text: "english buses",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 220,
      left: 8,
      width: 450,
      height: 150,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 60,
                left: 70,
                width: 35,
                height: 16,
                font: 12,
                type: "text",
                text: "is",
                valid: true,
              },
              {
                top: 60,
                left: 210,
                width: 70,
                height: 16,
                font: 12,
                type: "text",
                text: "has got",
                valid: true,
              },

              {
                top: 80,
                left: 70,
                width: 35,
                height: 16,
                font: 12,
                type: "text",
                text: "is",
                valid: true,
              },
              {
                top: 80,
                left: 210,
                width: 70,
                height: 16,
                font: 12,
                type: "text",
                text: "has got",
                valid: true,
              },
              {
                top: 100,
                left: 70,
                width: 35,
                height: 16,
                font: 12,
                type: "text",
                text: "is",
                valid: true,
              },
              {
                top: 100,
                left: 210,
                width: 70,
                height: 16,
                font: 12,
                type: "text",
                text: "has got",
                valid: true,
              },

              {
                top: 120,
                left: 70,
                width: 40,
                height: 16,
                font: 12,
                type: "text",
                text: "are",
                valid: true,
              },
              {
                top: 120,
                left: 210,
                width: 90,
                height: 16,
                font: 12,
                type: "text",
                text: "have got",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 370,
      left: 8,
      width: 450,
      height: 230,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 71,
                left: 70,
                textTopOverride:2,
                width: 73,
                height: 16,
                font: 12,
                type: "text",
                text: "have got",
                valid: true,
              },
              {
                top: 70,
                left: 250,
                textTopOverride:2,
                width: 50,
                height: 16,
                font: 12,
                type: "text",
                text: "Its",
                valid: true,
              },
              {
                top: 105,
                left: 70,
                width: 73,
                height: 16,
                font: 12,
                type: "text",
                text: "has got",
                valid: true,
              },
              {
                top: 105,
                left: 220,
                width: 60,
                height: 16,
                font: 12,
                type: "text",
                text: "Her",
                valid: true,
              },

              {
                top: 140,
                left: 70,
                width: 73,
                height: 16,
                font: 12,
                type: "text",
                text: "have got",
                valid: true,
              },
              {
                top: 140,
                left: 230,
                width: 65,
                height: 16,
                font: 12,
                type: "text",
                text: "your",
                valid: true,
              },

              {
                top: 175,
                left: 113,
                width: 70,
                height: 16,
                font: 12,
                type: "text",
                text: "has got",
                valid: true,
              },
              {
                top: 175,
                left: 230,
                width: 50,
                height: 16,
                font: 12,
                type: "text",
                text: "Their",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
