var comp_u_2_18 = {
    id: 18,
    paths: [
        {
          top: 40,
          left: 8,
          width: 450,
          height: 260,
          zoom: {
            answers: [
             
            ],
          },
        },
        {
          top: 300,
          left: 8,
          width: 450,
          height: 291,
          zoom: {
            answers: [
                {
                    paths: [
                     
        
                   
                      {
                        top: 165,
                        left: 60,
                        width: 130,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "has got",
                        valid: true,
                      },
                      {
                        top: 165,
                        left: 220,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "o",
                        valid: true,
                      },
                      {
                        top: 165,
                        left: 250,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "e",
                        valid: true,
                      },

                      {
                        top: 185,
                        left: 60,
                        width: 130,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "has got",
                        valid: true,
                      },
                      {
                        top: 185,
                        left: 220,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "o",
                        valid: true,
                      },
                      {
                        top: 185,
                        left: 250,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "s",
                        valid: true,
                      },
                      {
                        top: 205,
                        left: 60,
                        width: 130,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "have got",
                        valid: true,
                      },
                      {
                        top: 205,
                        left: 205,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "a",
                        valid: true,
                      },
                      {
                        top: 205,
                        left: 230,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "s",
                        valid: true,
                      },


                      {
                        top: 225,
                        left: 60,
                        width: 130,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "has got",
                        valid: true,
                      },
                      {
                        top: 228,
                        left: 205,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "e",
                        valid: true,
                      },
                      {
                        top: 229,
                        left: 240,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "ro",
                        valid: true,
                      },
                      {
                        top: 230,
                        left: 260,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "m",
                        valid: true,
                      },


                      {
                        top: 250,
                        left: 60,
                        width: 130,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "have got",
                        valid: true,
                      },
                      {
                        top: 249,
                        left: 195,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "g",
                        valid: true,
                      },
                      {
                        top: 249,
                        left: 229,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "r",
                        valid: true,
                      },
                      {
                        top: 249,
                        left: 248,
                        width: 50,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "e",
                        valid: true,
                      },
                    ],
                  },
            ],
          },
        },
      ],
    };
    