var comp_u_2_18 = {
    id: 18,
    paths: [
        {
          top: 40,
          left: 8,
          width: 450,
          height: 260,
          zoom: {
            answers: [
             
            ],
          },
        },
        {
          top: 300,
          left: 8,
          width: 450,
          height: 291,
          zoom: {
            answers: [
                {
                    paths: [
                     
        
                   
                      {
                        top: 165,
                        left: 60,
                        width: 120,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "has got",
                        valid: true,
                      },
                      {
                        top: 165,
                        left: 235,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "o",
                        valid: true,
                      },
                      {
                        top: 165,
                        left: 260,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "e",
                        valid: true,
                      },

                      {
                        top: 185,
                        left: 70,
                        width: 110,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "has got",
                        valid: true,
                      },
                      {
                        top: 185,
                        left: 235,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "o",
                        valid: true,
                      },
                      {
                        top: 185,
                        left: 260,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "s",
                        valid: true,
                      },
                      {
                        top: 205,
                        left: 70,
                        width: 110,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "have got",
                        valid: true,
                      },
                      {
                        top: 205,
                        left: 215,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "a",
                        valid: true,
                      },
                      {
                        top: 205,
                        left: 240,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "s",
                        valid: true,
                      },


                      {
                        top: 225,
                        left: 70,
                        width: 100,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "has got",
                        valid: true,
                      },
                      {
                        top: 226,
                        left: 225,
                        width: 15,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "e",
                        valid: true,
                      },
                      {
                        top: 226,
                        left: 252,
                        width: 15,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "ro",
                        valid: true,
                      },
                      {
                        top: 226,
                        left: 280,
                        width: 15,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "m",
                        valid: true,
                      },


                      {
                        top: 246,
                        left: 70,
                        width: 115,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "have got",
                        valid: true,
                      },
                      {
                        top: 248,
                        left: 213,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "g",
                        valid: true,
                      },
                      {
                        top: 249,
                        left: 240,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "r",
                        valid: true,
                      },
                      {
                        top: 249,
                        left: 265,
                        width: 20,
                        height: 16,
                        font: 12,
                        type: "text",
                        text: "e",
                        valid: true,
                      },
                    ],
                  },
            ],
          },
        },
      ],
    };
    