var apb_u_4_16 = {
  id: 16,
  paths: [
    {
      top: 300,
      left: 8,
      width: 450,
      height: 290,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 75,
                left: 130,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 75,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 147,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 97,
                left: 185,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 97,
                left: 204,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 122,
                left: 130,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 122,
                left: 147,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 122,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 122,
                left: 185,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 124,
                left:205 ,
                width: 16,
                height: 16,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 75,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 75,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 75,
                left: 400,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 100,
                left: 340,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 100,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                text: "o",
                valid: true,
              },
              {
                top: 100,
                left: 400,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 125,
                left: 340,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 125,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 123,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 220,
                left: 80,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 245,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 245,
                left: 86,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 265,
                left: 56,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 265,
                left: 86,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 265,
                left: 105,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 220,
                left: 220,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 245,
                left: 200,
                width: 16,
                height: 16,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 265,
                left: 225,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 220,
                left: 306,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
              {
                top: 220,
                left: 354,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 240,
                left: 330,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 240,
                left: 358,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 265,
                left: 306,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
              {
                top: 265,
                left: 336,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
              {
                top: 265,
                left: 358,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 8,
      width: 450,
      height: 280,
      zoom: {
        answers: [
          {
            paths: [
              {
                type: "underline",
                top: 80,
                left: 216,
                width: 70,
                rotate: 150,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 100,
                left: 210,
                width: 8,
                area: {
                    top: 100,
                    left: 210,
                    width: 8,
                    height: 8
                }, 
                underline: 1,
                type: "checkmark",
                valid: true
            },
            {
              type: "underline",
              top: 98,
              left: 214,
              width: 120,
              rotate: 150,
              text: "",
              valid: true,
              id: 2,
            },
            {
              top: 125,
              left: 210,
              width: 8,
              area: {
                  top: 125,
                  left: 210,
                  width: 8,
                  height: 8
              }, 
              underline: 2,
              type: "checkmark",
              valid: true
          },
          {
            type: "underline",
            top: 177,
            left: 212,
            width: 185,
            rotate: 197,
            text: "",
            valid: true,
            id: 3,
          },
          {
            top: 150,
            left: 210,
            width: 8,
            area: {
                top: 150,
                left: 210,
                width: 8,
                height: 8
            }, 
            underline: 3,
            type: "checkmark",
            valid: true
        },   
        {
          type: "underline",
          top: 171,
          left: 220,
          width: 165,
          rotate: 177,
          text: "",
          valid: true,
          id: 4,
        },
        {
          top: 175,
          left: 210,
          width: 8,
          area: {
              top: 175,
              left: 210,
              width: 8,
              height: 8
          }, 
          underline: 4,
          type: "checkmark",
          valid: true
      },  
      {
        type: "underline",
        top: 219,
        left: 215,
        width: 120,
        rotate:197,
        text: "",
        valid: true,
        id: 5,
      },
      {
        top: 200,
        left: 210,
        width: 8,
        area: {
            top: 200,
            left: 210,
            width: 8,
            height: 8
        }, 
        underline: 5,
        type: "checkmark",
        valid: true
    },   
    {
      type: "underline",
      top: 152,
      left: 191,
      width: 218,
      rotate: 136,
      text: "",
      valid: true,
      id: 6,
    },
    {
      top: 225,
      left: 210,
      width: 8,
      area: {
          top: 225,
          left: 210,
          width: 8,
          height: 8
      }, 
      underline: 6,
      type: "checkmark",
      valid: true
  }, 
  {
    type: "underline",
    top: 190,
    left: 200,
    width: 203,
    rotate: 142,
    text: "",
    valid: true,
    id: 7,
  },
  {
    top: 250,
    left: 210,
    width: 8,
    area: {
        top: 250,
        left: 210,
        width: 8,
        height: 8
    }, 
    underline: 7,
    type: "checkmark",
    valid: true
},  
            ],
          },
        ],
      },
    },
  ],
};
