var apb_u_4_16 = {
  id: 16,
  paths: [
    {
      top: 300,
      left: 8,
      width: 450,
      height: 290,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 75,
                left: 130,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 75,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 147,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 97,
                left: 185,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 97,
                left: 204,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 122,
                left: 130,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 122,
                left: 147,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 122,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 122,
                left: 185,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 124,
                left:205 ,
                width: 16,
                height: 16,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 75,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 75,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 75,
                left: 400,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 100,
                left: 340,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 100,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                text: "o",
                valid: true,
              },
              {
                top: 100,
                left: 400,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 125,
                left: 340,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 125,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 123,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 220,
                left: 80,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 245,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 245,
                left: 86,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                valid: true,
              },
              {
                top: 265,
                left: 56,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 265,
                left: 86,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 265,
                left: 105,
                width: 16,
                height: 16,
                type: "text",
                text: "d",
                valid: true,
              },
              {
                top: 220,
                left: 220,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 245,
                left: 200,
                width: 16,
                height: 16,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 265,
                left: 225,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 220,
                left: 306,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
              {
                top: 220,
                left: 354,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 240,
                left: 330,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 240,
                left: 358,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                valid: true,
              },
              {
                top: 265,
                left: 306,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
              {
                top: 265,
                left: 336,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
              {
                top: 265,
                left: 358,
                width: 16,
                height: 16,
                type: "text",
                text: "m",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 10,
      left: 8,
      width: 450,
      height: 280,
      zoom: {
        answers: [],
      },
    },
  ],
};
