var apb_u_4_17 = {
  id: 17,
  paths: [
    {
      top: 210,
      left: 8,
      width: 450,
      height: 390,
      zoom: {
        answers: [
          {
            paths: [
              
              {
                top: 60,
                left: 162,
                width: 43,
                height: 20,
                textTopOverride: -5,
                type: "text",
                text: "___",
                valid: true,
              },
                
              {
                top: 60,
                left: 50,
                width: 90,
                height: 30,
                type: "text",
                textTopOverride: -5,
                text: "__",
                valid: false,
              },
                  
              {
                top: 60,
                left: 267,
                width: 45,
                height: 30,
                type: "text",
                textTopOverride: -5,
                text: "__",
                valid: false,
              },
              
              {
                top: 85,
                left: 50,
                width: 45,
                height: 30,
                type: "text",
                textTopOverride: -6,
                text: "___",
                valid: true,
              },
              {
                top: 90,
                left: 162,
                width: 45,
                height: 30,
                type: "text",
                textTopOverride:4,
                text: "___",
                valid: false,
              },
              {
                top: 90,
                left: 267,
                width: 45,
                height: 30,
                type: "text",
                textTopOverride: 4,
                text: "___",
                valid: false,
              },
              {
                top: 120,
                left: 267,
                width: 45,
                textTopOverride:-10,
                height: 30,
                type: "text",
                text: "___",
                valid: true,
              },
              {
                top: 120,
                left: 162,
                width: 45,
                textTopOverride:-10,
                height: 30,
                type: "text",
                text: "___",
                valid: false,
              },
              {
                top: 120,
                left: 50,
                width: 45,
                textTopOverride:-10,
                height: 30,
                type: "text",
                text: "___",
                valid: false,
              },
              {
                top: 150,
                left: 154,
                width: 45,
                height: 30,
                type: "text",
                textTopOverride:-10,
                text: "__",
                valid: true,
              },
              {
                top: 150,
                left: 50,
                width: 45,
                height: 30,
                type: "text",
                textTopOverride:-10,
                text: "__",
                valid: false,
              },
              {
                top: 150,
                left: 267,
                width: 45,
                height: 30,
                type: "text",
                textTopOverride:-10,
                text: "__",
                valid:false,
              },
            ],
          },
        ],
      },
    },
    {
      top: 20,
      left: 8,
      width: 450,
      height: 190,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 54,
                left: 300,
                width: 20,
                height: 20,
                area: {
                  top: 55,
                  left: 285,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 54,
                left: 247,
                width: 20,
                height: 20,
                area: {
                  top: 55,
                  left: 285,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid:false,
              },
              {
                top: 54,
                left: 190,
                width: 20,
                height: 20,
                area: {
                  top: 55,
                  left: 285,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 54,
                left: 135,
                width: 20,
                height: 20,
                area: {
                  top: 55,
                  left: 285,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 87,
                left: 135,
                width: 20,
                height: 20,
                area: {
                  top: 200,
                  left: 160,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 87,
                left: 190,
                width: 20,
                height: 20,
                area: {
                  top: 200,
                  left: 160,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 87,
                left: 247,
                width: 20,
                height: 20,
                area: {
                  top: 200,
                  left: 160,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 87,
                left: 300,
                width: 20,
                height: 20,
                area: {
                  top: 200,
                  left: 160,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 120,
                left: 300,
                width: 20,
                height: 20,
                area: {
                  top: 124,
                  left: 247,
                  width: 40,
                  height: 8,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 120,
                left: 190,
                width: 20,
                height: 20,
                area: {
                  top: 200,
                  left: 160,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 120,
                left: 247,
                width: 20,
                height: 20,
                area: {
                  top: 200,
                  left: 160,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 120,
                left: 135,
                width: 20,
                height: 20,
                area: {
                  top: 200,
                  left: 160,
                  width: 40,
                  height: 40,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 152,
                left: 247,
                width: 20,
                height: 20,
                area: {
                  top: 123,
                  left: 336,
                  width: 40,
                  height: 8,
                },

                type: "multiple",
                valid: true,
              },
              {
                top: 152,
                left: 135,
                width: 20,
                height: 20,
                area: {
                  top: 123,
                  left: 336,
                  width: 40,
                  height: 8,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 152,
                left: 190,
                width: 20,
                height: 20,
                area: {
                  top: 123,
                  left: 336,
                  width: 40,
                  height: 8,
                },

                type: "multiple",
                valid: false,
              },
              {
                top: 152,
                left: 300,
                width: 20,
                height: 20,
                area: {
                  top: 123,
                  left: 336,
                  width: 40,
                  height: 8,
                },

                type: "multiple",
                valid:false,
              },
            ],
          },
        ],
      },
    },
  ],
};
