var apb_u_4_16 = {
  id: 16,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 280,
      zoom: {
        answers: [
          {
            paths: [
              {
                type: "underline",
                top: 83,
                left: 216,
                width: 70,
                rotate: 150,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 97,
                left: 214,
                width: 8,
                area: {
                  top: 97,
                  left: 214,
                  width: 8,
                  height: 8,
                },
                underline: 1,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 95,
                left: 214,
                width: 120,
                rotate: 150,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 123,
                left: 214,
                width: 8,
                area: {
                  top: 123,
                  left: 214,
                  width: 8,
                  height: 8,
                },
                underline: 2,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 177,
                left: 212,
                width: 185,
                rotate: 197,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 146,
                left: 214,
                width: 8,
                area: {
                  top: 146,
                  left: 214,
                  width: 8,
                  height: 8,
                },
                underline: 3,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 171,
                left: 220,
                width: 165,
                rotate: 177,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 172,
                left: 214,
                width: 8,
                area: {
                  top: 172,
                  left: 214,
                  width: 8,
                  height: 8,
                },
                underline: 4,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 219,
                left: 215,
                width: 120,
                rotate: 197,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 199,
                left: 214,
                width: 8,
                area: {
                  top: 199,
                  left: 214,
                  width: 8,
                  height: 8,
                },
                underline: 5,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 152,
                left: 191,
                width: 218,
                rotate: 136,
                text: "",
                valid: true,
                id: 6,
              },
              {
                top: 223,
                left: 214,
                width: 8,
                area: {
                  top: 223,
                  left: 214,
                  width: 8,
                  height: 8,
                },
                underline: 6,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 190,
                left: 200,
                width: 203,
                rotate: 142,
                text: "",
                valid: true,
                id: 7,
              },
              {
                top: 250,
                left: 214,
                width: 8,
                area: {
                  top: 250,
                  left: 214,
                  width: 8,
                  height: 8,
                },
                underline: 7,
                type: "checkmark",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 300,
      left: 8,
      width: 450,
      height: 290,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 75,
                left: 130,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "i",
                valid: true,
              },
              {
                top: 75,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 147,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 165,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 98,
                left: 185,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "g",
                valid: true,
              },
              {
                top: 100,
                left: 204,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "e",
                valid: true,
              },
              {
                top: 124,
                left: 130,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "e",
                valid: true,
              },
              {
                top: 124,
                left: 147,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 124,
                left: 167,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "c",
                valid: true,
              },
              {
                top: 124,
                left: 185,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "i",
                valid: true,
              },
              {
                top: 124,
                left: 205,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "l",
                valid: true,
              },
              {
                top: 75,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "e",
                valid: true,
              },
              {
                top: 75,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "e",
                valid: true,
              },
              {
                top: 75,
                left: 400,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 100,
                left: 342,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "e",
                valid: true,
              },
              {
                top: 100,
                left: 360,
                width: 16,
                height: 16,
                font: 16,
                type: "text",
                text: "l",
                valid: true,
              },
              {
                top: 100,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "o",
                valid: true,
              },
              {
                top: 100,
                left: 400,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 125,
                left: 340,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "i",
                valid: true,
              },
              {
                top: 125,
                left: 360,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 123,
                left: 380,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "g",
                valid: true,
              },
              {
                top: 220,
                left: 80,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "d",
                valid: true,
              },
              {
                top: 243,
                left: 60,
                width: 16,
                height: 16,
                type: "text",
                text: "b",
                font: 16,
                valid: true,
              },
              {
                top: 243,
                left: 86,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "b",
                valid: true,
              },
              {
                top: 265,
                left: 56,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "d",
                valid: true,
              },
              {
                top: 265,
                left: 86,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "d",
                valid: true,
              },
              {
                top: 265,
                left: 105,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "d",
                valid: true,
              },
              {
                top: 220,
                left: 220,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 243,
                left: 200,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "h",
                valid: true,
              },
              {
                top: 265,
                left: 225,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 220,
                left: 309,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "m",
                valid: true,
              },
              {
                top: 220,
                left: 354,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 243,
                left: 330,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "n",
                valid: true,
              },
              {
                top: 243,
                left: 358,
                width: 16,
                height: 16,
                type: "text",
                text: "n",
                font: 16,
                valid: true,
              },
              {
                top: 265,
                left: 309,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "m",
                valid: true,
              },
              {
                top: 265,
                left: 339,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "m",
                valid: true,
              },
              {
                top: 265,
                left: 358,
                width: 16,
                height: 16,
                type: "text",
                font: 16,
                text: "m",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
