var apb_u_3_12 = {
  id: 12,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 340,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 65,
                left: 55,
                width: 17,
                height: 16,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 65,
                left: 69,
                width: 17,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 65,
                left: 195,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 65,
                left: 210,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 65,
                left: 230,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 65,
                left: 250,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 65,
                left: 268,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 30,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 49,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 100,
                left: 65,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 100,
                left: 267,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 300,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 126,
                left: 150,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 126,
                left: 180,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 130,
                left: 235,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 130,
                left: 257,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 130,
                left: 275,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 20,
                left: 0,
                width: 16,
                height: 16,
                type: "text",
                text: "",
                valid: true,
              },
              {
                top: 163,
                left: 15,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 163,
                left: 50,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 163,
                left: 70,
                width: 16,
                height: 16,
                type: "text",
                text: "k",
                valid: true,
              },
              {
                top: 163,
                left: 85,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 240,
                left: 70,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 240,
                left: 104,
                width: 16,
                height: 16,
                type: "text",
                text: "f",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 360,
      left: 8,
      width: 450,
      height: 230,
      zoom: {
        answers: [],
      },
    },
  ],
};
