var apb_u_3_12 = {
  id: 12,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 340,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 65,
                left: 55,
                width: 17,
                height: 16,
                type: "text",
                text: "h",
                valid: true,
              },
              {
                top: 65,
                left: 69,
                width: 17,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 65,
                left: 195,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 65,
                left: 210,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 65,
                left: 230,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
              },
              {
                top: 65,
                left: 250,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 65,
                left: 268,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 30,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 49,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 100,
                left: 65,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 100,
                left: 267,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 100,
                left: 300,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 126,
                left: 150,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 126,
                left: 180,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 130,
                left: 235,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 130,
                left: 257,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
              },
              {
                top: 130,
                left: 275,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 20,
                left: 0,
                width: 16,
                height: 16,
                type: "text",
                text: "",
                valid: true,
              },
              {
                top: 163,
                left: 15,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 163,
                left: 50,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
              },
              {
                top: 163,
                left: 70,
                width: 16,
                height: 16,
                type: "text",
                text: "k",
                valid: true,
              },
              {
                top: 163,
                left: 85,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
              },
              {
                top: 240,
                left: 70,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
              },
              {
                top: 240,
                left: 104,
                width: 16,
                height: 16,
                type: "text",
                text: "f",
                valid: true,
              },
            ],
          },
        ],
      },
    },
    {
      top: 360,
      left: 8,
      width: 450,
      height: 230,
      zoom: {
        answers: [ 
          {
            paths: [
              {
                type: "underline",
                top: 127,
                left: 200,
                width: 190,
                rotate: 30,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 90,
                left: 200,
                width: 8,
                area: {
                    top: 90,
                    left: 200,
                    width: 8,
                    height: 8
                }, 
                underline: 1,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 71,
                left: 200,
                width: 190,
                rotate: -23,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 120,
                left: 200,
                width: 8,
                area: {
                    top: 120,
                    left: 200,
                    width: 8,
                    height: 8
                }, 
                underline: 2,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 174,
                left: 200,
                width: 120,
                rotate: 32,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 150,
                left: 200,
                width: 8,
                area: {
                    top: 150,
                    left: 200,
                    width: 8,
                    height: 8
                }, 
                underline: 3,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 108,
                left: 176,
                width: 170,
                rotate: -48,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 180,
                left: 200,
                width: 8,
                area: {
                    top: 180,
                    left: 200,
                    width: 8,
                    height: 8
                }, 
                underline: 4,
                type: "checkmark",
                valid: true
            },
              {
                type: "underline",
                top: 150,
                left: 187,
                width: 210,
                rotate: -32,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 210,
                left: 200,
                width: 8,
                area: {
                    top: 210,
                    left: 200,
                    width: 8,
                    height: 8
                }, 
                underline: 5,
                type: "checkmark",
                valid: true
            },
            ],
          },
        ],
      },
    },
  ],
};
