var apb_u_3_12 = {
  id: 12,
  paths: [
    {
      top: 10,
      left: 8,
      width: 450,
      height: 340,
      zoom: {
        answers: [
          {
            paths: [
              {
                top: 68,
                left: 55,
                width: 17,
                height: 16,
                type: "text",
                text: "h",
                valid: true,
                font: 16,
              },
              {
                top: 68,
                left: 69,
                width: 17,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 67,
                left: 195,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
                font: 16,
              },
              {
                top: 67,
                left: 210,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 67,
                left: 230,
                width: 16,
                height: 16,
                type: "text",
                text: "c",
                valid: true,
                font: 16,
              },
              {
                top: 67,
                left: 250,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 67,
                left: 268,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 103,
                left: 30,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 103,
                left: 49,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
                font: 16,
              },
              {
                top: 103,
                left: 65,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
                font: 16,
              },
              {
                top: 102,
                left: 267,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 102,
                left: 300,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 128,
                left: 150,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 128,
                left: 180,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 133,
                left: 235,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 133,
                left: 257,
                width: 16,
                height: 16,
                type: "text",
                text: "g",
                valid: true,
                font: 16,
              },
              {
                top: 133,
                left: 275,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 166,
                left: 15,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 166,
                left: 50,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
                font: 16,
              },
              {
                top: 166,
                left: 70,
                width: 16,
                height: 16,
                type: "text",
                text: "k",
                valid: true,
                font: 16,
              },
              {
                top: 166,
                left: 85,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
              {
                top: 243,
                left: 73,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 243,
                left: 104,
                width: 16,
                height: 16,
                type: "text",
                text: "f",
                valid: true,
                font: 16,
              },
              {
                top: 295,
                left: 234,
                width: 16,
                height: 16,
                type: "text",
                text: "a",
                valid: true,
                font: 16,
              },
              {
                top: 295,
                left: 259,
                width: 16,
                height: 16,
                type: "text",
                text: "k",
                valid: true,
                font: 16,
              },
              {
                top: 295,
                left: 280,
                width: 16,
                height: 16,
                type: "text",
                text: "i",
                valid: true,
                font: 16,
              },
              {
                top: 295,
                left: 307,
                width: 16,
                height: 16,
                type: "text",
                text: "e",
                valid: true,
                font: 16,
              },
            ],
          },
        ],
      },
    },
    {
      top: 360,
      left: 8,
      width: 450,
      height: 230,
      zoom: {
        answers: [
          {
            paths: [
              {
                type: "underline",
                top: 127,
                left: 200,
                width: 190,
                rotate: 30,
                text: "",
                valid: true,
                id: 1,
              },
              {
                top: 87,
                left: 203,
                width: 8,
                area: {
                  top: 87,
                  left: 203,
                  width: 8,
                  height: 8,
                },
                underline: 1,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 71,
                left: 200,
                width: 190,
                rotate: -23,
                text: "",
                valid: true,
                id: 2,
              },
              {
                top: 117,
                left: 203,
                width: 8,
                area: {
                  top: 117,
                  left: 203,
                  width: 8,
                  height: 8,
                },
                underline: 2,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 174,
                left: 200,
                width: 120,
                rotate: 32,
                text: "",
                valid: true,
                id: 3,
              },
              {
                top: 147,
                left: 203,
                width: 8,
                area: {
                  top: 147,
                  left: 203,
                  width: 8,
                  height: 8,
                },
                underline: 3,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 108,
                left: 176,
                width: 170,
                rotate: -48,
                text: "",
                valid: true,
                id: 4,
              },
              {
                top: 177,
                left: 203,
                width: 8,
                area: {
                  top: 177,
                  left: 203,
                  width: 8,
                  height: 8,
                },
                underline: 4,
                type: "checkmark",
                valid: true,
              },
              {
                type: "underline",
                top: 150,
                left: 187,
                width: 210,
                rotate: -32,
                text: "",
                valid: true,
                id: 5,
              },
              {
                top: 207,
                left: 203,
                width: 8,
                area: {
                  top: 207,
                  left: 203,
                  width: 8,
                  height: 8,
                },
                underline: 5,
                type: "checkmark",
                valid: true,
              },
            ],
          },
        ],
      },
    },
  ],
};
